//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Services.Esb.Dms.Document {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/")]
    public partial class DMSFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
                this.RaisePropertyChanged("codeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class metadata : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class folder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long folderIdField;
        
        private bool folderIdFieldSpecified;
        
        private string nameField;
        
        private long parentFolderIdField;
        
        private bool parentFolderIdFieldSpecified;
        
        private string tenantField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long folderId {
            get {
                return this.folderIdField;
            }
            set {
                this.folderIdField = value;
                this.RaisePropertyChanged("folderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool folderIdSpecified {
            get {
                return this.folderIdFieldSpecified;
            }
            set {
                this.folderIdFieldSpecified = value;
                this.RaisePropertyChanged("folderIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long parentFolderId {
            get {
                return this.parentFolderIdField;
            }
            set {
                this.parentFolderIdField = value;
                this.RaisePropertyChanged("parentFolderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentFolderIdSpecified {
            get {
                return this.parentFolderIdFieldSpecified;
            }
            set {
                this.parentFolderIdFieldSpecified = value;
                this.RaisePropertyChanged("parentFolderIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tenant {
            get {
                return this.tenantField;
            }
            set {
                this.tenantField = value;
                this.RaisePropertyChanged("tenant");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hitDocument))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class document : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private string categoryIdField;
        
        private string descriptionField;
        
        private string documentIdField;
        
        private string extensionField;
        
        private string fileStoragePathField;
        
        private long filesizeField;
        
        private bool filesizeFieldSpecified;
        
        private folder folderField;
        
        private metadata[] metadataField;
        
        private string modifiedAtField;
        
        private string nameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string documentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("documentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
                this.RaisePropertyChanged("extension");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fileStoragePath {
            get {
                return this.fileStoragePathField;
            }
            set {
                this.fileStoragePathField = value;
                this.RaisePropertyChanged("fileStoragePath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long filesize {
            get {
                return this.filesizeField;
            }
            set {
                this.filesizeField = value;
                this.RaisePropertyChanged("filesize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool filesizeSpecified {
            get {
                return this.filesizeFieldSpecified;
            }
            set {
                this.filesizeFieldSpecified = value;
                this.RaisePropertyChanged("filesizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public folder folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
                this.RaisePropertyChanged("folder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry")]
        public metadata[] metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string modifiedAt {
            get {
                return this.modifiedAtField;
            }
            set {
                this.modifiedAtField = value;
                this.RaisePropertyChanged("modifiedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class hitDocument : document {
        
        private hitDocumentEntry[] highlightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public hitDocumentEntry[] highlight {
            get {
                return this.highlightField;
            }
            set {
                this.highlightField = value;
                this.RaisePropertyChanged("highlight");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class hitDocumentEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", ConfigurationName="Dms.Document.DocumentService")]
    public interface DocumentService {
        
        // CODEGEN: Parameter 'content' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Dms.Document.updateDocumentResponse updateDocument(WebEas.Services.Esb.Dms.Document.updateDocument request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.readFolderDocumentsResponse readFolderDocuments(WebEas.Services.Esb.Dms.Document.readFolderDocuments request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.readDocumentContentResponse readDocumentContent(WebEas.Services.Esb.Dms.Document.readDocumentContent request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void moveFolderDocuments(string tenant, long folderId, long newFolderId);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.readFoldersResponse readFolders(WebEas.Services.Esb.Dms.Document.readFolders request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        long createFolder(string tenant, long parentFolderId, string name);
        
        // CODEGEN: Parameter 'content' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.createDocumentResponse createDocument(WebEas.Services.Esb.Dms.Document.createDocument request);
        
        // CODEGEN: Parameter 'metadata' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.findDocumentsResponse findDocuments(WebEas.Services.Esb.Dms.Document.findDocuments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void moveFolder(string tenant, long folderId, long parentFolderId);
        
        // CODEGEN: Parameter 'metadata' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.findAllDocumentsResponse findAllDocuments(WebEas.Services.Esb.Dms.Document.findAllDocuments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void renameFolder(string tenant, long folderId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool deleteFolder(string tenant, long folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void deleteDocument(string tenant, string documentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebEas.Services.Esb.Dms.Document.document readDocumentById(string tenant, string documentId, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Dms.Document.DMSFault), Action="*", Name="DMSFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool clearMetadata(string tenant, string documentId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDocument", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class updateDocument {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public WebEas.Services.Esb.Dms.Document.document document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content;
        
        public updateDocument() {
        }
        
        public updateDocument(string tenant, WebEas.Services.Esb.Dms.Document.document document, byte[] content) {
            this.tenant = tenant;
            this.document = document;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateDocumentResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class updateDocumentResponse {
        
        public updateDocumentResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFolderDocuments", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readFolderDocuments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public long folderId;
        
        public readFolderDocuments() {
        }
        
        public readFolderDocuments(string tenant, long folderId) {
            this.tenant = tenant;
            this.folderId = folderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFolderDocumentsResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readFolderDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public WebEas.Services.Esb.Dms.Document.document[] @return;
        
        public readFolderDocumentsResponse() {
        }
        
        public readFolderDocumentsResponse(WebEas.Services.Esb.Dms.Document.document[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readDocumentContent", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readDocumentContent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public string documentId;
        
        public readDocumentContent() {
        }
        
        public readDocumentContent(string tenant, string documentId) {
            this.tenant = tenant;
            this.documentId = documentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readDocumentContentResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readDocumentContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] @return;
        
        public readDocumentContentResponse() {
        }
        
        public readDocumentContentResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFolders", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readFolders {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public long folderId;
        
        public readFolders() {
        }
        
        public readFolders(string tenant, long folderId) {
            this.tenant = tenant;
            this.folderId = folderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readFoldersResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class readFoldersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return")]
        public WebEas.Services.Esb.Dms.Document.folder[] @return;
        
        public readFoldersResponse() {
        }
        
        public readFoldersResponse(WebEas.Services.Esb.Dms.Document.folder[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDocument", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class createDocument {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public string categoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=2)]
        public WebEas.Services.Esb.Dms.Document.document document;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] content;
        
        public createDocument() {
        }
        
        public createDocument(string tenant, string categoryId, WebEas.Services.Esb.Dms.Document.document document, byte[] content) {
            this.tenant = tenant;
            this.categoryId = categoryId;
            this.document = document;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createDocumentResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class createDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string @return;
        
        public createDocumentResponse() {
        }
        
        public createDocumentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://params.api.dms.dwcslovakia.sk")]
    public partial class searchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private hitDocument[] documentsField;
        
        private long pageField;
        
        private long totalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documents", IsNullable=true, Order=0)]
        public hitDocument[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
                this.RaisePropertyChanged("documents");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
                this.RaisePropertyChanged("page");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDocuments", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class findDocuments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("metadata")]
        public WebEas.Services.Esb.Dms.Document.metadata[] metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=3)]
        public bool highlight;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=4)]
        public long fromPage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=5)]
        public long pageSize;
        
        public findDocuments() {
        }
        
        public findDocuments(string tenant, string query, WebEas.Services.Esb.Dms.Document.metadata[] metadata, bool highlight, long fromPage, long pageSize) {
            this.tenant = tenant;
            this.query = query;
            this.metadata = metadata;
            this.highlight = highlight;
            this.fromPage = fromPage;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findDocumentsResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class findDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public WebEas.Services.Esb.Dms.Document.searchResult @return;
        
        public findDocumentsResponse() {
        }
        
        public findDocumentsResponse(WebEas.Services.Esb.Dms.Document.searchResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllDocuments", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class findAllDocuments {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public string tenant;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=1)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("metadata")]
        public WebEas.Services.Esb.Dms.Document.metadata[] metadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=3)]
        public bool highlight;
        
        public findAllDocuments() {
        }
        
        public findAllDocuments(string tenant, string query, WebEas.Services.Esb.Dms.Document.metadata[] metadata, bool highlight) {
            this.tenant = tenant;
            this.query = query;
            this.metadata = metadata;
            this.highlight = highlight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllDocumentsResponse", WrapperNamespace="http://document.api.dms.dwcslovakia.sk/", IsWrapped=true)]
    public partial class findAllDocumentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://document.api.dms.dwcslovakia.sk/", Order=0)]
        public WebEas.Services.Esb.Dms.Document.searchResult @return;
        
        public findAllDocumentsResponse() {
        }
        
        public findAllDocumentsResponse(WebEas.Services.Esb.Dms.Document.searchResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentServiceChannel : WebEas.Services.Esb.Dms.Document.DocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<WebEas.Services.Esb.Dms.Document.DocumentService>, WebEas.Services.Esb.Dms.Document.DocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.updateDocumentResponse WebEas.Services.Esb.Dms.Document.DocumentService.updateDocument(WebEas.Services.Esb.Dms.Document.updateDocument request) {
            return base.Channel.updateDocument(request);
        }
        
        public void updateDocument(string tenant, WebEas.Services.Esb.Dms.Document.document document, byte[] content) {
            WebEas.Services.Esb.Dms.Document.updateDocument inValue = new WebEas.Services.Esb.Dms.Document.updateDocument();
            inValue.tenant = tenant;
            inValue.document = document;
            inValue.content = content;
            WebEas.Services.Esb.Dms.Document.updateDocumentResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).updateDocument(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.readFolderDocumentsResponse WebEas.Services.Esb.Dms.Document.DocumentService.readFolderDocuments(WebEas.Services.Esb.Dms.Document.readFolderDocuments request) {
            return base.Channel.readFolderDocuments(request);
        }
        
        public WebEas.Services.Esb.Dms.Document.document[] readFolderDocuments(string tenant, long folderId) {
            WebEas.Services.Esb.Dms.Document.readFolderDocuments inValue = new WebEas.Services.Esb.Dms.Document.readFolderDocuments();
            inValue.tenant = tenant;
            inValue.folderId = folderId;
            WebEas.Services.Esb.Dms.Document.readFolderDocumentsResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).readFolderDocuments(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.readDocumentContentResponse WebEas.Services.Esb.Dms.Document.DocumentService.readDocumentContent(WebEas.Services.Esb.Dms.Document.readDocumentContent request) {
            return base.Channel.readDocumentContent(request);
        }
        
        public byte[] readDocumentContent(string tenant, string documentId) {
            WebEas.Services.Esb.Dms.Document.readDocumentContent inValue = new WebEas.Services.Esb.Dms.Document.readDocumentContent();
            inValue.tenant = tenant;
            inValue.documentId = documentId;
            WebEas.Services.Esb.Dms.Document.readDocumentContentResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).readDocumentContent(inValue);
            return retVal.@return;
        }
        
        public void moveFolderDocuments(string tenant, long folderId, long newFolderId) {
            base.Channel.moveFolderDocuments(tenant, folderId, newFolderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.readFoldersResponse WebEas.Services.Esb.Dms.Document.DocumentService.readFolders(WebEas.Services.Esb.Dms.Document.readFolders request) {
            return base.Channel.readFolders(request);
        }
        
        public WebEas.Services.Esb.Dms.Document.folder[] readFolders(string tenant, long folderId) {
            WebEas.Services.Esb.Dms.Document.readFolders inValue = new WebEas.Services.Esb.Dms.Document.readFolders();
            inValue.tenant = tenant;
            inValue.folderId = folderId;
            WebEas.Services.Esb.Dms.Document.readFoldersResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).readFolders(inValue);
            return retVal.@return;
        }
        
        public long createFolder(string tenant, long parentFolderId, string name) {
            return base.Channel.createFolder(tenant, parentFolderId, name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.createDocumentResponse WebEas.Services.Esb.Dms.Document.DocumentService.createDocument(WebEas.Services.Esb.Dms.Document.createDocument request) {
            return base.Channel.createDocument(request);
        }
        
        public string createDocument(string tenant, string categoryId, WebEas.Services.Esb.Dms.Document.document document, byte[] content) {
            WebEas.Services.Esb.Dms.Document.createDocument inValue = new WebEas.Services.Esb.Dms.Document.createDocument();
            inValue.tenant = tenant;
            inValue.categoryId = categoryId;
            inValue.document = document;
            inValue.content = content;
            WebEas.Services.Esb.Dms.Document.createDocumentResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).createDocument(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.findDocumentsResponse WebEas.Services.Esb.Dms.Document.DocumentService.findDocuments(WebEas.Services.Esb.Dms.Document.findDocuments request) {
            return base.Channel.findDocuments(request);
        }
        
        public WebEas.Services.Esb.Dms.Document.searchResult findDocuments(string tenant, string query, WebEas.Services.Esb.Dms.Document.metadata[] metadata, bool highlight, long fromPage, long pageSize) {
            WebEas.Services.Esb.Dms.Document.findDocuments inValue = new WebEas.Services.Esb.Dms.Document.findDocuments();
            inValue.tenant = tenant;
            inValue.query = query;
            inValue.metadata = metadata;
            inValue.highlight = highlight;
            inValue.fromPage = fromPage;
            inValue.pageSize = pageSize;
            WebEas.Services.Esb.Dms.Document.findDocumentsResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).findDocuments(inValue);
            return retVal.@return;
        }
        
        public void moveFolder(string tenant, long folderId, long parentFolderId) {
            base.Channel.moveFolder(tenant, folderId, parentFolderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Dms.Document.findAllDocumentsResponse WebEas.Services.Esb.Dms.Document.DocumentService.findAllDocuments(WebEas.Services.Esb.Dms.Document.findAllDocuments request) {
            return base.Channel.findAllDocuments(request);
        }
        
        public WebEas.Services.Esb.Dms.Document.searchResult findAllDocuments(string tenant, string query, WebEas.Services.Esb.Dms.Document.metadata[] metadata, bool highlight) {
            WebEas.Services.Esb.Dms.Document.findAllDocuments inValue = new WebEas.Services.Esb.Dms.Document.findAllDocuments();
            inValue.tenant = tenant;
            inValue.query = query;
            inValue.metadata = metadata;
            inValue.highlight = highlight;
            WebEas.Services.Esb.Dms.Document.findAllDocumentsResponse retVal = ((WebEas.Services.Esb.Dms.Document.DocumentService)(this)).findAllDocuments(inValue);
            return retVal.@return;
        }
        
        public void renameFolder(string tenant, long folderId, string name) {
            base.Channel.renameFolder(tenant, folderId, name);
        }
        
        public bool deleteFolder(string tenant, long folderId) {
            return base.Channel.deleteFolder(tenant, folderId);
        }
        
        public void deleteDocument(string tenant, string documentId) {
            base.Channel.deleteDocument(tenant, documentId);
        }
        
        public WebEas.Services.Esb.Dms.Document.document readDocumentById(string tenant, string documentId, string version) {
            return base.Channel.readDocumentById(tenant, documentId, version);
        }
        
        public bool clearMetadata(string tenant, string documentId) {
            return base.Channel.clearMetadata(tenant, documentId);
        }
    }
}
