//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Services.Esb.Egov.LapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcomFault", Namespace="http://schemas.dcom.sk/fault/1.0")]
    [System.SerializableAttribute()]
    public partial class dcomFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faultCauseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int faultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string faultMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebEas.Services.Esb.Egov.LapService.InvalidParameterType[] invalidParameterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faultCause {
            get {
                return this.faultCauseField;
            }
            set {
                if ((object.ReferenceEquals(this.faultCauseField, value) != true)) {
                    this.faultCauseField = value;
                    this.RaisePropertyChanged("faultCause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                if ((this.faultCodeField.Equals(value) != true)) {
                    this.faultCodeField = value;
                    this.RaisePropertyChanged("faultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.faultMessageField, value) != true)) {
                    this.faultMessageField = value;
                    this.RaisePropertyChanged("faultMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebEas.Services.Esb.Egov.LapService.InvalidParameterType[] invalidParameter {
            get {
                return this.invalidParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.invalidParameterField, value) != true)) {
                    this.invalidParameterField = value;
                    this.RaisePropertyChanged("invalidParameter");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidParameterType", Namespace="http://schemas.dcom.sk/fault/1.0")]
    [System.SerializableAttribute()]
    public partial class InvalidParameterType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parameterNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errorMessageField, value) != true)) {
                    this.errorMessageField = value;
                    this.RaisePropertyChanged("errorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parameterName {
            get {
                return this.parameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parameterNameField, value) != true)) {
                    this.parameterNameField = value;
                    this.RaisePropertyChanged("parameterName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dcom.sk/public/egov/wcf/1.0", ConfigurationName="Egov.LapService.ILapService")]
    public interface ILapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidence", ReplyAction="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidenceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Egov.LapService.dcomFault), Action="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidence/Fault/SoapF" +
            "ault", Name="dcomFault", Namespace="http://schemas.dcom.sk/fault/1.0")]
        void SaveToEvidence(long dPodanieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidenceXml", ReplyAction="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidenceXmlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Egov.LapService.dcomFault), Action="http://schemas.dcom.sk/public/egov/wcf/1.0/ILapService/SaveToEvidenceXml/Fault/So" +
            "apFault", Name="dcomFault", Namespace="http://schemas.dcom.sk/fault/1.0")]
        void SaveToEvidenceXml(long dPodanieId, string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILapServiceChannel : WebEas.Services.Esb.Egov.LapService.ILapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LapServiceClient : System.ServiceModel.ClientBase<WebEas.Services.Esb.Egov.LapService.ILapService>, WebEas.Services.Esb.Egov.LapService.ILapService {
        
        public LapServiceClient() {
        }
        
        public LapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveToEvidence(long dPodanieId) {
            base.Channel.SaveToEvidence(dPodanieId);
        }
        
        public void SaveToEvidenceXml(long dPodanieId, string xml) {
            base.Channel.SaveToEvidenceXml(dPodanieId, xml);
        }
    }
}
