# place project specific paths in variables to make the rest of the script more generic
variables:
  TEST_FOLDER: 'Tests\bin\Release'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe'
  NUNIT_PATH: 'C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe'

stages:
  - build

build_job:
  stage: build
  script:
    - '& ./setVersion.ps1 "0.0.0.$env:CI_JOB_ID"'
    - '& "$env:MSBUILD_PATH" /p:Configuration="$env:CI_COMMIT_REF_NAME" /t:restore' # restore package references
    - '& "$env:MSBUILD_PATH" eSam.sln /p:Configuration="$env:CI_COMMIT_REF_NAME" /p:DeployOnBuild=true /p:PublishProfile="$env:CI_COMMIT_REF_NAME"Profile.pubxml' # build the project
    - 'foreach ($file in Get-ChildItem Deploy\*.cmd) {echo "Running $file"; & $file /Y /M:http://sd1esambe01.datalan.sk/MSDeployAgentService}'
  only:
    - develop