//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Services.Esb.Rsd {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/fault/1.0")]
    public partial class DcomFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int faultCodeField;
        
        private string faultMessageField;
        
        private string faultCauseField;
        
        private InvalidParameterType[] invalidParameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int faultCode {
            get {
                return this.faultCodeField;
            }
            set {
                this.faultCodeField = value;
                this.RaisePropertyChanged("faultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultMessage {
            get {
                return this.faultMessageField;
            }
            set {
                this.faultMessageField = value;
                this.RaisePropertyChanged("faultMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string faultCause {
            get {
                return this.faultCauseField;
            }
            set {
                this.faultCauseField = value;
                this.RaisePropertyChanged("faultCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invalidParameter", Order=3)]
        public InvalidParameterType[] invalidParameter {
            get {
                return this.invalidParameterField;
            }
            set {
                this.invalidParameterField = value;
                this.RaisePropertyChanged("invalidParameter");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/fault/1.0")]
    public partial class InvalidParameterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parameterNameField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string parameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
                this.RaisePropertyChanged("parameterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ReviewedPersonType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private ReviewedPersonRoleType roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
                this.RaisePropertyChanged("ToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReviewedPersonRoleType Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ReviewedPersonRoleType : EnumerationType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReviewedPersonRoleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BenefitTypeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public abstract partial class EnumerationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class BenefitTypeType : EnumerationType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class PaymentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal amountField;
        
        private System.DateTime dateField;
        
        private string placeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
                this.RaisePropertyChanged("Place");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ClaimType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private string typeField;
        
        private decimal amountField;
        
        private PaymentType paymentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PaymentType Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
                this.RaisePropertyChanged("Payment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ApplicationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BenefitTypeType benefitTypeField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        private ClaimType[] claimField;
        
        private ReviewedPersonType[] reviewedPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BenefitTypeType BenefitType {
            get {
                return this.benefitTypeField;
            }
            set {
                this.benefitTypeField = value;
                this.RaisePropertyChanged("BenefitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ToSpecified {
            get {
                return this.toFieldSpecified;
            }
            set {
                this.toFieldSpecified = value;
                this.RaisePropertyChanged("ToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Claim", Order=3)]
        public ClaimType[] Claim {
            get {
                return this.claimField;
            }
            set {
                this.claimField = value;
                this.RaisePropertyChanged("Claim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReviewedPerson", Order=4)]
        public ReviewedPersonType[] ReviewedPerson {
            get {
                return this.reviewedPersonField;
            }
            set {
                this.reviewedPersonField = value;
                this.RaisePropertyChanged("ReviewedPerson");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ApplicantResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long recordIDField;
        
        private bool recordIDFieldSpecified;
        
        private IdentificationResultType identificationResultField;
        
        private ApplicationType[] applicationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIDSpecified {
            get {
                return this.recordIDFieldSpecified;
            }
            set {
                this.recordIDFieldSpecified = value;
                this.RaisePropertyChanged("RecordIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdentificationResultType IdentificationResult {
            get {
                return this.identificationResultField;
            }
            set {
                this.identificationResultField = value;
                this.RaisePropertyChanged("IdentificationResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Application", Order=2)]
        public ApplicationType[] Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
                this.RaisePropertyChanged("Application");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public enum IdentificationResultType {
        
        /// <remarks/>
        found,
        
        /// <remarks/>
        not_found,
        
        /// <remarks/>
        ambiguous,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class ApplicantRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dcomIDField;
        
        private string dossierIDField;
        
        private System.DateTime claimFromField;
        
        private System.DateTime claimToField;
        
        private bool claimToFieldSpecified;
        
        private BenefitTypeType benefitTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DcomID {
            get {
                return this.dcomIDField;
            }
            set {
                this.dcomIDField = value;
                this.RaisePropertyChanged("DcomID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DossierID {
            get {
                return this.dossierIDField;
            }
            set {
                this.dossierIDField = value;
                this.RaisePropertyChanged("DossierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime ClaimFrom {
            get {
                return this.claimFromField;
            }
            set {
                this.claimFromField = value;
                this.RaisePropertyChanged("ClaimFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime ClaimTo {
            get {
                return this.claimToField;
            }
            set {
                this.claimToField = value;
                this.RaisePropertyChanged("ClaimTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClaimToSpecified {
            get {
                return this.claimToFieldSpecified;
            }
            set {
                this.claimToFieldSpecified = value;
                this.RaisePropertyChanged("ClaimToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public BenefitTypeType BenefitType {
            get {
                return this.benefitTypeField;
            }
            set {
                this.benefitTypeField = value;
                this.RaisePropertyChanged("BenefitType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0", ConfigurationName="Rsd.RSDGateway")]
    public interface RSDGateway {
        
        // CODEGEN: Generating message contract since the operation GetFamilyRelatedBenefitsForApplicant is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetFamilyRelatedBenefitsForApplicant", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Rsd.DcomFaultType), Action="*", Name="DcomFaultMessage", Namespace="http://schemas.dcom.sk/fault/1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnumerationType))]
        WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantRes GetFamilyRelatedBenefitsForApplicant(WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantReq request);
        
        // CODEGEN: Generating message contract since the operation GetMaterialNeedBenefitsForApplicant is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetMaterialNeedBenefitsForApplicant", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Rsd.DcomFaultType), Action="*", Name="DcomFaultMessage", Namespace="http://schemas.dcom.sk/fault/1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnumerationType))]
        WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantRes GetMaterialNeedBenefitsForApplicant(WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantReq request);
        
        // CODEGEN: Generating message contract since the operation GetHealthDisabilityBenefitsForApplicant is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetHealthDisabilityBenefitsForApplicant", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Rsd.DcomFaultType), Action="*", Name="DcomFaultMessage", Namespace="http://schemas.dcom.sk/fault/1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnumerationType))]
        WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantRes GetHealthDisabilityBenefitsForApplicant(WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantReq request);
        
        // CODEGEN: Generating message contract since the operation GetPersonDisabilityStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPersonDisabilityStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Rsd.DcomFaultType), Action="*", Name="DcomFaultMessage", Namespace="http://schemas.dcom.sk/fault/1.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EnumerationType))]
        WebEas.Services.Esb.Rsd.getPersonDisabilityStatusRes GetPersonDisabilityStatus(WebEas.Services.Esb.Rsd.getPersonDisabilityStatusReq request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFamilyRelatedBenefitsForApplicantReq {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFamilyRelatedBenefitsForApplicantReq", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantRequest GetFamilyRelatedBenefitsForApplicantReq1;
        
        public getFamilyRelatedBenefitsForApplicantReq() {
        }
        
        public getFamilyRelatedBenefitsForApplicantReq(WebEas.Services.Esb.Rsd.ApplicantRequest GetFamilyRelatedBenefitsForApplicantReq1) {
            this.GetFamilyRelatedBenefitsForApplicantReq1 = GetFamilyRelatedBenefitsForApplicantReq1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFamilyRelatedBenefitsForApplicantRes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFamilyRelatedBenefitsForApplicantRes", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetFamilyRelatedBenefitsForApplicantRes1;
        
        public getFamilyRelatedBenefitsForApplicantRes() {
        }
        
        public getFamilyRelatedBenefitsForApplicantRes(WebEas.Services.Esb.Rsd.ApplicantResponse GetFamilyRelatedBenefitsForApplicantRes1) {
            this.GetFamilyRelatedBenefitsForApplicantRes1 = GetFamilyRelatedBenefitsForApplicantRes1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaterialNeedBenefitsForApplicantReq {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaterialNeedBenefitsForApplicantReq", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantRequest GetMaterialNeedBenefitsForApplicantReq1;
        
        public getMaterialNeedBenefitsForApplicantReq() {
        }
        
        public getMaterialNeedBenefitsForApplicantReq(WebEas.Services.Esb.Rsd.ApplicantRequest GetMaterialNeedBenefitsForApplicantReq1) {
            this.GetMaterialNeedBenefitsForApplicantReq1 = GetMaterialNeedBenefitsForApplicantReq1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMaterialNeedBenefitsForApplicantRes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaterialNeedBenefitsForApplicantRes", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetMaterialNeedBenefitsForApplicantRes1;
        
        public getMaterialNeedBenefitsForApplicantRes() {
        }
        
        public getMaterialNeedBenefitsForApplicantRes(WebEas.Services.Esb.Rsd.ApplicantResponse GetMaterialNeedBenefitsForApplicantRes1) {
            this.GetMaterialNeedBenefitsForApplicantRes1 = GetMaterialNeedBenefitsForApplicantRes1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHealthDisabilityBenefitsForApplicantReq {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHealthDisabilityBenefitsForApplicantReq", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantRequest GetHealthDisabilityBenefitsForApplicantReq1;
        
        public getHealthDisabilityBenefitsForApplicantReq() {
        }
        
        public getHealthDisabilityBenefitsForApplicantReq(WebEas.Services.Esb.Rsd.ApplicantRequest GetHealthDisabilityBenefitsForApplicantReq1) {
            this.GetHealthDisabilityBenefitsForApplicantReq1 = GetHealthDisabilityBenefitsForApplicantReq1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHealthDisabilityBenefitsForApplicantRes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHealthDisabilityBenefitsForApplicantRes", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetHealthDisabilityBenefitsForApplicantRes1;
        
        public getHealthDisabilityBenefitsForApplicantRes() {
        }
        
        public getHealthDisabilityBenefitsForApplicantRes(WebEas.Services.Esb.Rsd.ApplicantResponse GetHealthDisabilityBenefitsForApplicantRes1) {
            this.GetHealthDisabilityBenefitsForApplicantRes1 = GetHealthDisabilityBenefitsForApplicantRes1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class GetPersonDisabilityStatusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dcomIDField;
        
        private string dossierIDField;
        
        private System.DateTime dateOfInterestField;
        
        private bool dateOfInterestFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DcomID {
            get {
                return this.dcomIDField;
            }
            set {
                this.dcomIDField = value;
                this.RaisePropertyChanged("DcomID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DossierID {
            get {
                return this.dossierIDField;
            }
            set {
                this.dossierIDField = value;
                this.RaisePropertyChanged("DossierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime DateOfInterest {
            get {
                return this.dateOfInterestField;
            }
            set {
                this.dateOfInterestField = value;
                this.RaisePropertyChanged("DateOfInterest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateOfInterestSpecified {
            get {
                return this.dateOfInterestFieldSpecified;
            }
            set {
                this.dateOfInterestFieldSpecified = value;
                this.RaisePropertyChanged("DateOfInterestSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class GetPersonDisabilityStatusResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long recordIDField;
        
        private bool recordIDFieldSpecified;
        
        private IdentificationResultType identificationResultField;
        
        private DisabilityType disabilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordIDSpecified {
            get {
                return this.recordIDFieldSpecified;
            }
            set {
                this.recordIDFieldSpecified = value;
                this.RaisePropertyChanged("RecordIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdentificationResultType IdentificationResult {
            get {
                return this.identificationResultField;
            }
            set {
                this.identificationResultField = value;
                this.RaisePropertyChanged("IdentificationResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DisabilityType Disability {
            get {
                return this.disabilityField;
            }
            set {
                this.disabilityField = value;
                this.RaisePropertyChanged("Disability");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/rsd/1.0")]
    public partial class DisabilityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool accompanyingPersonField;
        
        private System.DateTime dateOfAssessmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool AccompanyingPerson {
            get {
                return this.accompanyingPersonField;
            }
            set {
                this.accompanyingPersonField = value;
                this.RaisePropertyChanged("AccompanyingPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DateOfAssessment {
            get {
                return this.dateOfAssessmentField;
            }
            set {
                this.dateOfAssessmentField = value;
                this.RaisePropertyChanged("DateOfAssessment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonDisabilityStatusReq {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonDisabilityStatusReq", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusRequest GetPersonDisabilityStatusReq1;
        
        public getPersonDisabilityStatusReq() {
        }
        
        public getPersonDisabilityStatusReq(WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusRequest GetPersonDisabilityStatusReq1) {
            this.GetPersonDisabilityStatusReq1 = GetPersonDisabilityStatusReq1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonDisabilityStatusRes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonDisabilityStatusRes", Namespace="http://schemas.dcom.sk/integration/rsd/1.0", Order=0)]
        public WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusResponse GetPersonDisabilityStatusRes1;
        
        public getPersonDisabilityStatusRes() {
        }
        
        public getPersonDisabilityStatusRes(WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusResponse GetPersonDisabilityStatusRes1) {
            this.GetPersonDisabilityStatusRes1 = GetPersonDisabilityStatusRes1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RSDGatewayChannel : WebEas.Services.Esb.Rsd.RSDGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RSDGatewayClient : System.ServiceModel.ClientBase<WebEas.Services.Esb.Rsd.RSDGateway>, WebEas.Services.Esb.Rsd.RSDGateway {
        
        public RSDGatewayClient() {
        }
        
        public RSDGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RSDGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSDGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RSDGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantRes WebEas.Services.Esb.Rsd.RSDGateway.GetFamilyRelatedBenefitsForApplicant(WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantReq request) {
            return base.Channel.GetFamilyRelatedBenefitsForApplicant(request);
        }
        
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetFamilyRelatedBenefitsForApplicant(WebEas.Services.Esb.Rsd.ApplicantRequest GetFamilyRelatedBenefitsForApplicantReq1) {
            WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantReq inValue = new WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantReq();
            inValue.GetFamilyRelatedBenefitsForApplicantReq1 = GetFamilyRelatedBenefitsForApplicantReq1;
            WebEas.Services.Esb.Rsd.getFamilyRelatedBenefitsForApplicantRes retVal = ((WebEas.Services.Esb.Rsd.RSDGateway)(this)).GetFamilyRelatedBenefitsForApplicant(inValue);
            return retVal.GetFamilyRelatedBenefitsForApplicantRes1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantRes WebEas.Services.Esb.Rsd.RSDGateway.GetMaterialNeedBenefitsForApplicant(WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantReq request) {
            return base.Channel.GetMaterialNeedBenefitsForApplicant(request);
        }
        
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetMaterialNeedBenefitsForApplicant(WebEas.Services.Esb.Rsd.ApplicantRequest GetMaterialNeedBenefitsForApplicantReq1) {
            WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantReq inValue = new WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantReq();
            inValue.GetMaterialNeedBenefitsForApplicantReq1 = GetMaterialNeedBenefitsForApplicantReq1;
            WebEas.Services.Esb.Rsd.getMaterialNeedBenefitsForApplicantRes retVal = ((WebEas.Services.Esb.Rsd.RSDGateway)(this)).GetMaterialNeedBenefitsForApplicant(inValue);
            return retVal.GetMaterialNeedBenefitsForApplicantRes1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantRes WebEas.Services.Esb.Rsd.RSDGateway.GetHealthDisabilityBenefitsForApplicant(WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantReq request) {
            return base.Channel.GetHealthDisabilityBenefitsForApplicant(request);
        }
        
        public WebEas.Services.Esb.Rsd.ApplicantResponse GetHealthDisabilityBenefitsForApplicant(WebEas.Services.Esb.Rsd.ApplicantRequest GetHealthDisabilityBenefitsForApplicantReq1) {
            WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantReq inValue = new WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantReq();
            inValue.GetHealthDisabilityBenefitsForApplicantReq1 = GetHealthDisabilityBenefitsForApplicantReq1;
            WebEas.Services.Esb.Rsd.getHealthDisabilityBenefitsForApplicantRes retVal = ((WebEas.Services.Esb.Rsd.RSDGateway)(this)).GetHealthDisabilityBenefitsForApplicant(inValue);
            return retVal.GetHealthDisabilityBenefitsForApplicantRes1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Rsd.getPersonDisabilityStatusRes WebEas.Services.Esb.Rsd.RSDGateway.GetPersonDisabilityStatus(WebEas.Services.Esb.Rsd.getPersonDisabilityStatusReq request) {
            return base.Channel.GetPersonDisabilityStatus(request);
        }
        
        public WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusResponse GetPersonDisabilityStatus(WebEas.Services.Esb.Rsd.GetPersonDisabilityStatusRequest GetPersonDisabilityStatusReq1) {
            WebEas.Services.Esb.Rsd.getPersonDisabilityStatusReq inValue = new WebEas.Services.Esb.Rsd.getPersonDisabilityStatusReq();
            inValue.GetPersonDisabilityStatusReq1 = GetPersonDisabilityStatusReq1;
            WebEas.Services.Esb.Rsd.getPersonDisabilityStatusRes retVal = ((WebEas.Services.Esb.Rsd.RSDGateway)(this)).GetPersonDisabilityStatus(inValue);
            return retVal.GetPersonDisabilityStatusRes1;
        }
    }
}
