//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Esam.ServiceInterface.Office.Reg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebEas.Esam.ServiceInterface.Office.Reg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Importni/Mergni Pokladnice
        ///MERGE INTO reg.C_Pokladnica AS Target 
        ///USING 
        ///    (SELECT Rok, nazov_knihy, ID_Kniha, ISNULL(m.C_Mena_Id, 978), 
        ///        ROW_NUMBER() OVER (ORDER BY ID_Kniha) + ISNULL((SELECT MAX(CAST(KOD AS INT)) FROM reg.C_Pokladnica WHERE ISNUMERIC(KOD) = 1), 0)
        ///     FROM KORWIN.DB_FROM.dbo.UC_POKLADNA_KNIHA p
        ///     LEFT JOIN reg.C_Mena m ON m.Kod COLLATE SQL_Slovak_CP1250_CI_AS = p.kod
        ///     WHERE Rok IN (CASE WHEN (SELECT COUNT(*) FROM KORWIN.DB_FROM.dbo.UC_POKLADNA_KNIHA WHERE Rok = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Korwin_POK {
            get {
                return ResourceManager.GetString("Korwin_POK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO reg.C_Projekt AS Target 
        ///USING 
        ///    (SELECT ID_PROJEKT, 
        ///        ROW_NUMBER() OVER (ORDER BY ID_PROJEKT) + ISNULL((SELECT MAX(CAST(KOD AS INT)) FROM reg.C_Projekt WHERE ISNUMERIC(KOD) = 1), 0), 
        ///        NAZOV + CASE WHEN COUNT(NAZOV) OVER (PARTITION BY NAZOV) &gt; 1 THEN &apos; - &apos; + CAST(ID_PROJEKT AS VARCHAR) ELSE &apos;&apos; END NAZOV, 
        ///        POPIS
        ///     --FROM KORWIN.DB_FROM.ESAM.PROJEKTY()) AS source (ID_PROJEKT, PORADIE, NAZOV, POPIS) 
        ///     FROM OPENQUERY(KORWIN, &apos;SELECT * FROM DB_FROM.ESAM.PROJEKTY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Korwin_PRJ {
            get {
                return ResourceManager.GetString("Korwin_PRJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO reg.C_Stredisko AS Target 
        ///USING 
        ///    (SELECT ID_STREDISKO, 
        ///        ROW_NUMBER() OVER (ORDER BY ID_STREDISKO)  + ISNULL((SELECT MAX(CAST(KOD AS INT)) FROM reg.C_Stredisko WHERE ISNUMERIC(KOD) = 1), 0),
        ///        NAZOV + CASE WHEN COUNT(NAZOV) OVER (PARTITION BY NAZOV) &gt; 1 THEN &apos; - &apos; + CAST(ID_STREDISKO AS VARCHAR) ELSE &apos;&apos; END NAZOV, 
        ///        POPIS
        ///     FROM OPENQUERY(KORWIN, &apos;SELECT * FROM DB_FROM.ESAM.STREDISKA()&apos;)
        ///    ) AS source (ID_STREDISKO, PORADIE, NAZOV, POPIS)
        ///ON Target.C_Stredisk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Korwin_STR {
            get {
                return ResourceManager.GetString("Korwin_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO reg.C_BankaUcet AS Target 
        ///USING 
        ///    (SELECT ID_ucet, Kod_Banky, 
        ///    CASE WHEN COUNT(nazov_banky) OVER (PARTITION BY nazov_banky) &gt; 1 THEN RIGHT(IBAN, 4) + &apos; - &apos; ELSE &apos;&apos; END + nazov_banky, 
        ///    ISNULL(iban, &apos;SK0000000000000&apos;) + CASE WHEN ROW_NUMBER() OVER (PARTITION BY iban order by iban) &gt; 1 THEN &apos;-&apos; + CAST(ID_Ucet AS VARCHAR) ELSE &apos;&apos; END AS IBAN,
        ///    ISNULL(m.C_Mena_Id, 978), BIC
        ///    FROM KORWIN.DB_FROM.dbo.UC_ORGANIZACIA_UCTY u
        ///    LEFT JOIN reg.C_Mena m ON m.Kod COLLATE SQL_Slovak_CP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Korwin_VBU {
            get {
                return ResourceManager.GetString("Korwin_VBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Import/Merge Pokladnice
        ///MERGE INTO reg.C_Pokladnica AS Target 
        ///USING 
        ///    (SELECT ROK, p.NAZOV, ID_POKLADNICA, ISNULL(m.C_Mena_Id, 978), 
        ///        ROW_NUMBER() OVER (ORDER BY ID_POKLADNICA) + ISNULL((SELECT MAX(CAST(KOD AS INT)) FROM reg.C_Pokladnica WHERE ISNUMERIC(KOD) = 1), 0), p.PLATNOSTOD, p.PLATNOSTDO, POPIS, DCOM
        ///     FROM OPENQUERY(URBIS, &apos;SELECT * FROM DB_FROM.ESAM.POKLADNICE(@YEAR)&apos;) p
        ///     LEFT JOIN reg.C_Mena m ON m.Kod COLLATE SQL_Slovak_CP1250_CI_AS = p.MENA)
        ///        AS source (ROK, N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Urbis_POK {
            get {
                return ResourceManager.GetString("Urbis_POK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO reg.C_Stredisko AS Target 
        ///USING 
        ///    (SELECT ID_STREDISKO, 
        ///        ROW_NUMBER() OVER (ORDER BY ID_STREDISKO)  + ISNULL((SELECT MAX(CAST(KOD AS INT)) FROM reg.C_Stredisko WHERE ISNUMERIC(KOD) = 1), 0),
        ///        NAZOV + CASE WHEN COUNT(NAZOV) OVER (PARTITION BY NAZOV) &gt; 1 THEN &apos; - &apos; + CAST(ID_STREDISKO AS VARCHAR) ELSE &apos;&apos; END NAZOV, 
        ///        POPIS, PLATNOSTOD, DATUMPLATNOSTI
        ///     FROM OPENQUERY(URBIS, &apos;SELECT * FROM DB_FROM.ESAM.STREDISKA(@YEAR)&apos;)
        ///    ) AS source (ID_STREDISKO, PORADIE, NAZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Urbis_STR {
            get {
                return ResourceManager.GetString("Urbis_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO reg.C_BankaUcet AS Target 
        ///USING 
        ///    (SELECT IDUCET, KBAN, 
        ///    CASE WHEN COUNT(u.NAZOV) OVER (PARTITION BY u.NAZOV) &gt; 1 THEN RIGHT(IBAN, 4) + &apos; - &apos; ELSE &apos;&apos; END + u.NAZOV, 
        ///    ISNULL(iban, &apos;SK0000000000000&apos;) + CASE WHEN ROW_NUMBER() OVER (PARTITION BY iban order by iban) &gt; 1 THEN &apos;-&apos; + CAST(IDUCET AS VARCHAR) ELSE &apos;&apos; END AS IBAN,
        ///    ISNULL(m.C_Mena_Id, 978), BIC
        ///    FROM OPENQUERY(URBIS, &apos;SELECT * FROM DB_FROM.ESAM.BANKOVEUCTY(@YEAR)&apos;) u
        ///     LEFT JOIN reg.C_Mena m ON m.Kod COLLATE SQL_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Urbis_VBU {
            get {
                return ResourceManager.GetString("Urbis_VBU", resourceCulture);
            }
        }
    }
}
