//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Services.Esb.Bpm2 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class BpmFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private string codeField;
        
        private InvalidParameter[] invalidParameterFaultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public InvalidParameter[] InvalidParameterFault {
            get {
                return this.invalidParameterFaultField;
            }
            set {
                this.invalidParameterFaultField = value;
                this.RaisePropertyChanged("InvalidParameterFault");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class InvalidParameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string parameterNameField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string parameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
                this.RaisePropertyChanged("parameterName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class Variable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class SubmitTaskFormRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskIdField;
        
        private Variable[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", ConfigurationName="Bpm2.BpmServicePortType")]
    public interface BpmServicePortType {
        
        // CODEGEN: Generating message contract since the operation SubmitTaskForm is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.SubmitTaskFormResponse SubmitTaskForm(WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CompleteTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.CompleteTaskResponse CompleteTask(WebEas.Services.Esb.Bpm2.CompleteTaskRequest1 request);
        
        // CODEGEN: Generating message contract since the operation StartProcessInstance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/bpm/StartProcessInstance", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse1 StartProcessInstance(WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetProcessVariables is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/bpm/GetProcessVariables", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse1 GetProcessVariables(WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetSingleTask is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.GetSingleTaskResponse1 GetSingleTask(WebEas.Services.Esb.Bpm2.GetSingleTaskRequest1 request);
        
        // CODEGEN: Generating message contract since the operation SetAssignee is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.SetAssigneeResponse SetAssignee(WebEas.Services.Esb.Bpm2.SetAssigneeRequest1 request);
        
        // CODEGEN: Generating message contract since the operation SendMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/bpm/SendMessage", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.SendMessageResponse SendMessage(WebEas.Services.Esb.Bpm2.SendMessageRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetUserAgenda is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/bpm/GetUserAgenda", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.GetUserAgendaResponse GetUserAgenda(WebEas.Services.Esb.Bpm2.GetUserAgendaRequest request);
        
        // CODEGEN: Generating message contract since the operation GetProcessInstances is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/bpm/GetProcessInstances", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.GetProcessInstancesResponse GetProcessInstances(WebEas.Services.Esb.Bpm2.GetProcessInstancesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetUserAgendaCount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.Services.Esb.Bpm2.BpmFault), Action="*", Name="BpmFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebEas.Services.Esb.Bpm2.GetUserAgendaCountResponse GetUserAgendaCount(WebEas.Services.Esb.Bpm2.GetUserAgendaCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitTaskFormRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest SubmitTaskFormRequest;
        
        public SubmitTaskFormRequest1() {
        }
        
        public SubmitTaskFormRequest1(WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest SubmitTaskFormRequest) {
            this.SubmitTaskFormRequest = SubmitTaskFormRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitTaskFormResponse {
        
        public SubmitTaskFormResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class CompleteTaskRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskIdField;
        
        private Variable[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteTaskRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.CompleteTaskRequest CompleteTaskRequest;
        
        public CompleteTaskRequest1() {
        }
        
        public CompleteTaskRequest1(WebEas.Services.Esb.Bpm2.CompleteTaskRequest CompleteTaskRequest) {
            this.CompleteTaskRequest = CompleteTaskRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CompleteTaskResponse {
        
        public CompleteTaskResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class StartProcessInstanceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string businessKeyField;
        
        private string modulNameField;
        
        private Variable[] variablesField;
        
        private ProcessDefinition processDefinitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string businessKey {
            get {
                return this.businessKeyField;
            }
            set {
                this.businessKeyField = value;
                this.RaisePropertyChanged("businessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string modulName {
            get {
                return this.modulNameField;
            }
            set {
                this.modulNameField = value;
                this.RaisePropertyChanged("modulName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ProcessDefinition ProcessDefinition {
            get {
                return this.processDefinitionField;
            }
            set {
                this.processDefinitionField = value;
                this.RaisePropertyChanged("ProcessDefinition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class ProcessDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("key", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        id,
        
        /// <remarks/>
        key,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class StartProcessInstanceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string processDefinitionIdField;
        
        private string businessKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string processDefinitionId {
            get {
                return this.processDefinitionIdField;
            }
            set {
                this.processDefinitionIdField = value;
                this.RaisePropertyChanged("processDefinitionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string businessKey {
            get {
                return this.businessKeyField;
            }
            set {
                this.businessKeyField = value;
                this.RaisePropertyChanged("businessKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessInstanceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest StartProcessInstanceRequest;
        
        public StartProcessInstanceRequest1() {
        }
        
        public StartProcessInstanceRequest1(WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest StartProcessInstanceRequest) {
            this.StartProcessInstanceRequest = StartProcessInstanceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartProcessInstanceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse StartProcessInstanceResponse;
        
        public StartProcessInstanceResponse1() {
        }
        
        public StartProcessInstanceResponse1(WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse StartProcessInstanceResponse) {
            this.StartProcessInstanceResponse = StartProcessInstanceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class GetProcessVariablesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string processInstanceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string processInstanceId {
            get {
                return this.processInstanceIdField;
            }
            set {
                this.processInstanceIdField = value;
                this.RaisePropertyChanged("processInstanceId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class GetProcessVariablesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Variable[] variablesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessVariablesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest GetProcessVariablesRequest;
        
        public GetProcessVariablesRequest1() {
        }
        
        public GetProcessVariablesRequest1(WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest GetProcessVariablesRequest) {
            this.GetProcessVariablesRequest = GetProcessVariablesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessVariablesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse GetProcessVariablesResponse;
        
        public GetProcessVariablesResponse1() {
        }
        
        public GetProcessVariablesResponse1(WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse GetProcessVariablesResponse) {
            this.GetProcessVariablesResponse = GetProcessVariablesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class GetSingleTaskRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class GetSingleTaskResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Task taskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Task Task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
                this.RaisePropertyChanged("Task");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class Task : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string assigneeField;
        
        private System.DateTime createdField;
        
        private System.DateTime dueField;
        
        private bool dueFieldSpecified;
        
        private string descriptionField;
        
        private string executionIdField;
        
        private string ownerField;
        
        private string parentTaskIdField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        private string processDefinitionIdField;
        
        private string processInstanceIdField;
        
        private string taskDefinitionKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string assignee {
            get {
                return this.assigneeField;
            }
            set {
                this.assigneeField = value;
                this.RaisePropertyChanged("assignee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime due {
            get {
                return this.dueField;
            }
            set {
                this.dueField = value;
                this.RaisePropertyChanged("due");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueSpecified {
            get {
                return this.dueFieldSpecified;
            }
            set {
                this.dueFieldSpecified = value;
                this.RaisePropertyChanged("dueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string executionId {
            get {
                return this.executionIdField;
            }
            set {
                this.executionIdField = value;
                this.RaisePropertyChanged("executionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
                this.RaisePropertyChanged("owner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string parentTaskId {
            get {
                return this.parentTaskIdField;
            }
            set {
                this.parentTaskIdField = value;
                this.RaisePropertyChanged("parentTaskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
                this.RaisePropertyChanged("prioritySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string processDefinitionId {
            get {
                return this.processDefinitionIdField;
            }
            set {
                this.processDefinitionIdField = value;
                this.RaisePropertyChanged("processDefinitionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string processInstanceId {
            get {
                return this.processInstanceIdField;
            }
            set {
                this.processInstanceIdField = value;
                this.RaisePropertyChanged("processInstanceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string taskDefinitionKey {
            get {
                return this.taskDefinitionKeyField;
            }
            set {
                this.taskDefinitionKeyField = value;
                this.RaisePropertyChanged("taskDefinitionKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSingleTaskRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.GetSingleTaskRequest GetSingleTaskRequest;
        
        public GetSingleTaskRequest1() {
        }
        
        public GetSingleTaskRequest1(WebEas.Services.Esb.Bpm2.GetSingleTaskRequest GetSingleTaskRequest) {
            this.GetSingleTaskRequest = GetSingleTaskRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSingleTaskResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.GetSingleTaskResponse GetSingleTaskResponse;
        
        public GetSingleTaskResponse1() {
        }
        
        public GetSingleTaskResponse1(WebEas.Services.Esb.Bpm2.GetSingleTaskResponse GetSingleTaskResponse) {
            this.GetSingleTaskResponse = GetSingleTaskResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class SetAssigneeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
                this.RaisePropertyChanged("taskId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAssigneeRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.SetAssigneeRequest SetAssigneeRequest;
        
        public SetAssigneeRequest1() {
        }
        
        public SetAssigneeRequest1(WebEas.Services.Esb.Bpm2.SetAssigneeRequest SetAssigneeRequest) {
            this.SetAssigneeRequest = SetAssigneeRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAssigneeResponse {
        
        public SetAssigneeResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class SendMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageNameField;
        
        private string businessKeyField;
        
        private Variable[] variablesField;
        
        private Variable[] correlationKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string messageName {
            get {
                return this.messageNameField;
            }
            set {
                this.messageNameField = value;
                this.RaisePropertyChanged("messageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string businessKey {
            get {
                return this.businessKeyField;
            }
            set {
                this.businessKeyField = value;
                this.RaisePropertyChanged("businessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] Variables {
            get {
                return this.variablesField;
            }
            set {
                this.variablesField = value;
                this.RaisePropertyChanged("Variables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Variable[] CorrelationKeys {
            get {
                return this.correlationKeysField;
            }
            set {
                this.correlationKeysField = value;
                this.RaisePropertyChanged("CorrelationKeys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.SendMessageRequest SendMessageRequest;
        
        public SendMessageRequest1() {
        }
        
        public SendMessageRequest1(WebEas.Services.Esb.Bpm2.SendMessageRequest SendMessageRequest) {
            this.SendMessageRequest = SendMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        public SendMessageResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class UserAgendaRequestDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string[] tenantIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tenantIds", Order=1)]
        public string[] tenantIds {
            get {
                return this.tenantIdsField;
            }
            set {
                this.tenantIdsField = value;
                this.RaisePropertyChanged("tenantIds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class UserAgendaItemDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int countField;
        
        private string tenantIdField;
        
        private System.DateTime lastCreateDateField;
        
        private bool lastCreateDateFieldSpecified;
        
        private string urlField;
        
        private int moduleIdField;
        
        private AggregationCategory aggregationCategoryField;
        
        private bool aggregationCategoryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("tenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime lastCreateDate {
            get {
                return this.lastCreateDateField;
            }
            set {
                this.lastCreateDateField = value;
                this.RaisePropertyChanged("lastCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastCreateDateSpecified {
            get {
                return this.lastCreateDateFieldSpecified;
            }
            set {
                this.lastCreateDateFieldSpecified = value;
                this.RaisePropertyChanged("lastCreateDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int moduleId {
            get {
                return this.moduleIdField;
            }
            set {
                this.moduleIdField = value;
                this.RaisePropertyChanged("moduleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public AggregationCategory aggregationCategory {
            get {
                return this.aggregationCategoryField;
            }
            set {
                this.aggregationCategoryField = value;
                this.RaisePropertyChanged("aggregationCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aggregationCategorySpecified {
            get {
                return this.aggregationCategoryFieldSpecified;
            }
            set {
                this.aggregationCategoryFieldSpecified = value;
                this.RaisePropertyChanged("aggregationCategorySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public enum AggregationCategory {
        
        /// <remarks/>
        userAgenda,
        
        /// <remarks/>
        nonProcessedSubmission,
        
        /// <remarks/>
        incorrectSubmission,
        
        /// <remarks/>
        openRecords,
        
        /// <remarks/>
        processedSubmission,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAgendaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.UserAgendaRequestDto UserAgendaRequestDto;
        
        public GetUserAgendaRequest() {
        }
        
        public GetUserAgendaRequest(WebEas.Services.Esb.Bpm2.UserAgendaRequestDto UserAgendaRequestDto) {
            this.UserAgendaRequestDto = UserAgendaRequestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAgendaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WebEas.Services.Esb.Bpm2.UserAgendaItemDto[] UserAgendaResponseDto;
        
        public GetUserAgendaResponse() {
        }
        
        public GetUserAgendaResponse(WebEas.Services.Esb.Bpm2.UserAgendaItemDto[] UserAgendaResponseDto) {
            this.UserAgendaResponseDto = UserAgendaResponseDto;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class GetProcessInstancesRequestDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string processDefinitionKeyField;
        
        private string[] businessKeysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string processDefinitionKey {
            get {
                return this.processDefinitionKeyField;
            }
            set {
                this.processDefinitionKeyField = value;
                this.RaisePropertyChanged("processDefinitionKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("businessKeys", Order=1)]
        public string[] businessKeys {
            get {
                return this.businessKeysField;
            }
            set {
                this.businessKeysField = value;
                this.RaisePropertyChanged("businessKeys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class ProcessInstanceDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string businessKeyField;
        
        private bool isAliveField;
        
        private TaskDto[] taskDtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string businessKey {
            get {
                return this.businessKeyField;
            }
            set {
                this.businessKeyField = value;
                this.RaisePropertyChanged("businessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool isAlive {
            get {
                return this.isAliveField;
            }
            set {
                this.isAliveField = value;
                this.RaisePropertyChanged("isAlive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaskDto", Order=3)]
        public TaskDto[] TaskDto {
            get {
                return this.taskDtoField;
            }
            set {
                this.taskDtoField = value;
                this.RaisePropertyChanged("TaskDto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class TaskDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string assigneeField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string assignee {
            get {
                return this.assigneeField;
            }
            set {
                this.assigneeField = value;
                this.RaisePropertyChanged("assignee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessInstancesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.GetProcessInstancesRequestDto GetProcessInstancesRequestDto;
        
        public GetProcessInstancesRequest() {
        }
        
        public GetProcessInstancesRequest(WebEas.Services.Esb.Bpm2.GetProcessInstancesRequestDto GetProcessInstancesRequestDto) {
            this.GetProcessInstancesRequestDto = GetProcessInstancesRequestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcessInstancesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WebEas.Services.Esb.Bpm2.ProcessInstanceDto[] GetProcessInstancesResponseDto;
        
        public GetProcessInstancesResponse() {
        }
        
        public GetProcessInstancesResponse(WebEas.Services.Esb.Bpm2.ProcessInstanceDto[] GetProcessInstancesResponseDto) {
            this.GetProcessInstancesResponseDto = GetProcessInstancesResponseDto;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class UserAgendaCountRequestDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int daysOldThresholdField;
        
        private bool daysOldThresholdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int daysOldThreshold {
            get {
                return this.daysOldThresholdField;
            }
            set {
                this.daysOldThresholdField = value;
                this.RaisePropertyChanged("daysOldThreshold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool daysOldThresholdSpecified {
            get {
                return this.daysOldThresholdFieldSpecified;
            }
            set {
                this.daysOldThresholdFieldSpecified = value;
                this.RaisePropertyChanged("daysOldThresholdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class UserAgendaCountResponseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long myTaskCountField;
        
        private long myTaskCountOldField;
        
        private System.DateTime myLastTaskTimeField;
        
        private bool myLastTaskTimeFieldSpecified;
        
        private UserAgendaCountGroupTasksDto[] userAgendaCountGroupTasksDtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long myTaskCount {
            get {
                return this.myTaskCountField;
            }
            set {
                this.myTaskCountField = value;
                this.RaisePropertyChanged("myTaskCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long myTaskCountOld {
            get {
                return this.myTaskCountOldField;
            }
            set {
                this.myTaskCountOldField = value;
                this.RaisePropertyChanged("myTaskCountOld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime myLastTaskTime {
            get {
                return this.myLastTaskTimeField;
            }
            set {
                this.myLastTaskTimeField = value;
                this.RaisePropertyChanged("myLastTaskTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool myLastTaskTimeSpecified {
            get {
                return this.myLastTaskTimeFieldSpecified;
            }
            set {
                this.myLastTaskTimeFieldSpecified = value;
                this.RaisePropertyChanged("myLastTaskTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserAgendaCountGroupTasksDto", Order=3)]
        public UserAgendaCountGroupTasksDto[] UserAgendaCountGroupTasksDto {
            get {
                return this.userAgendaCountGroupTasksDtoField;
            }
            set {
                this.userAgendaCountGroupTasksDtoField = value;
                this.RaisePropertyChanged("UserAgendaCountGroupTasksDto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0")]
    public partial class UserAgendaCountGroupTasksDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string groupNameField;
        
        private long taskCountField;
        
        private long taskCountOldField;
        
        private System.DateTime lastTaskTimeField;
        
        private bool lastTaskTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
                this.RaisePropertyChanged("groupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long taskCount {
            get {
                return this.taskCountField;
            }
            set {
                this.taskCountField = value;
                this.RaisePropertyChanged("taskCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long taskCountOld {
            get {
                return this.taskCountOldField;
            }
            set {
                this.taskCountOldField = value;
                this.RaisePropertyChanged("taskCountOld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime lastTaskTime {
            get {
                return this.lastTaskTimeField;
            }
            set {
                this.lastTaskTimeField = value;
                this.RaisePropertyChanged("lastTaskTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTaskTimeSpecified {
            get {
                return this.lastTaskTimeFieldSpecified;
            }
            set {
                this.lastTaskTimeFieldSpecified = value;
                this.RaisePropertyChanged("lastTaskTimeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAgendaCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.UserAgendaCountRequestDto UserAgendaCountRequestDto;
        
        public GetUserAgendaCountRequest() {
        }
        
        public GetUserAgendaCountRequest(WebEas.Services.Esb.Bpm2.UserAgendaCountRequestDto UserAgendaCountRequestDto) {
            this.UserAgendaCountRequestDto = UserAgendaCountRequestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAgendaCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/bpm/2.0", Order=0)]
        public WebEas.Services.Esb.Bpm2.UserAgendaCountResponseDto UserAgendaCountResponseDto;
        
        public GetUserAgendaCountResponse() {
        }
        
        public GetUserAgendaCountResponse(WebEas.Services.Esb.Bpm2.UserAgendaCountResponseDto UserAgendaCountResponseDto) {
            this.UserAgendaCountResponseDto = UserAgendaCountResponseDto;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BpmServicePortTypeChannel : WebEas.Services.Esb.Bpm2.BpmServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BpmServicePortTypeClient : System.ServiceModel.ClientBase<WebEas.Services.Esb.Bpm2.BpmServicePortType>, WebEas.Services.Esb.Bpm2.BpmServicePortType {
        
        public BpmServicePortTypeClient() {
        }
        
        public BpmServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BpmServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BpmServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BpmServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.SubmitTaskFormResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.SubmitTaskForm(WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest1 request) {
            return base.Channel.SubmitTaskForm(request);
        }
        
        public void SubmitTaskForm(WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest SubmitTaskFormRequest) {
            WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest1 inValue = new WebEas.Services.Esb.Bpm2.SubmitTaskFormRequest1();
            inValue.SubmitTaskFormRequest = SubmitTaskFormRequest;
            WebEas.Services.Esb.Bpm2.SubmitTaskFormResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).SubmitTaskForm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.CompleteTaskResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.CompleteTask(WebEas.Services.Esb.Bpm2.CompleteTaskRequest1 request) {
            return base.Channel.CompleteTask(request);
        }
        
        public void CompleteTask(WebEas.Services.Esb.Bpm2.CompleteTaskRequest CompleteTaskRequest) {
            WebEas.Services.Esb.Bpm2.CompleteTaskRequest1 inValue = new WebEas.Services.Esb.Bpm2.CompleteTaskRequest1();
            inValue.CompleteTaskRequest = CompleteTaskRequest;
            WebEas.Services.Esb.Bpm2.CompleteTaskResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).CompleteTask(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse1 WebEas.Services.Esb.Bpm2.BpmServicePortType.StartProcessInstance(WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest1 request) {
            return base.Channel.StartProcessInstance(request);
        }
        
        public WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse StartProcessInstance(WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest StartProcessInstanceRequest) {
            WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest1 inValue = new WebEas.Services.Esb.Bpm2.StartProcessInstanceRequest1();
            inValue.StartProcessInstanceRequest = StartProcessInstanceRequest;
            WebEas.Services.Esb.Bpm2.StartProcessInstanceResponse1 retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).StartProcessInstance(inValue);
            return retVal.StartProcessInstanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse1 WebEas.Services.Esb.Bpm2.BpmServicePortType.GetProcessVariables(WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest1 request) {
            return base.Channel.GetProcessVariables(request);
        }
        
        public WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse GetProcessVariables(WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest GetProcessVariablesRequest) {
            WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest1 inValue = new WebEas.Services.Esb.Bpm2.GetProcessVariablesRequest1();
            inValue.GetProcessVariablesRequest = GetProcessVariablesRequest;
            WebEas.Services.Esb.Bpm2.GetProcessVariablesResponse1 retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).GetProcessVariables(inValue);
            return retVal.GetProcessVariablesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.GetSingleTaskResponse1 WebEas.Services.Esb.Bpm2.BpmServicePortType.GetSingleTask(WebEas.Services.Esb.Bpm2.GetSingleTaskRequest1 request) {
            return base.Channel.GetSingleTask(request);
        }
        
        public WebEas.Services.Esb.Bpm2.GetSingleTaskResponse GetSingleTask(WebEas.Services.Esb.Bpm2.GetSingleTaskRequest GetSingleTaskRequest) {
            WebEas.Services.Esb.Bpm2.GetSingleTaskRequest1 inValue = new WebEas.Services.Esb.Bpm2.GetSingleTaskRequest1();
            inValue.GetSingleTaskRequest = GetSingleTaskRequest;
            WebEas.Services.Esb.Bpm2.GetSingleTaskResponse1 retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).GetSingleTask(inValue);
            return retVal.GetSingleTaskResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.SetAssigneeResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.SetAssignee(WebEas.Services.Esb.Bpm2.SetAssigneeRequest1 request) {
            return base.Channel.SetAssignee(request);
        }
        
        public void SetAssignee(WebEas.Services.Esb.Bpm2.SetAssigneeRequest SetAssigneeRequest) {
            WebEas.Services.Esb.Bpm2.SetAssigneeRequest1 inValue = new WebEas.Services.Esb.Bpm2.SetAssigneeRequest1();
            inValue.SetAssigneeRequest = SetAssigneeRequest;
            WebEas.Services.Esb.Bpm2.SetAssigneeResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).SetAssignee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.SendMessageResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.SendMessage(WebEas.Services.Esb.Bpm2.SendMessageRequest1 request) {
            return base.Channel.SendMessage(request);
        }
        
        public void SendMessage(WebEas.Services.Esb.Bpm2.SendMessageRequest SendMessageRequest) {
            WebEas.Services.Esb.Bpm2.SendMessageRequest1 inValue = new WebEas.Services.Esb.Bpm2.SendMessageRequest1();
            inValue.SendMessageRequest = SendMessageRequest;
            WebEas.Services.Esb.Bpm2.SendMessageResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).SendMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.GetUserAgendaResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.GetUserAgenda(WebEas.Services.Esb.Bpm2.GetUserAgendaRequest request) {
            return base.Channel.GetUserAgenda(request);
        }
        
        public WebEas.Services.Esb.Bpm2.UserAgendaItemDto[] GetUserAgenda(WebEas.Services.Esb.Bpm2.UserAgendaRequestDto UserAgendaRequestDto) {
            WebEas.Services.Esb.Bpm2.GetUserAgendaRequest inValue = new WebEas.Services.Esb.Bpm2.GetUserAgendaRequest();
            inValue.UserAgendaRequestDto = UserAgendaRequestDto;
            WebEas.Services.Esb.Bpm2.GetUserAgendaResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).GetUserAgenda(inValue);
            return retVal.UserAgendaResponseDto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.GetProcessInstancesResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.GetProcessInstances(WebEas.Services.Esb.Bpm2.GetProcessInstancesRequest request) {
            return base.Channel.GetProcessInstances(request);
        }
        
        public WebEas.Services.Esb.Bpm2.ProcessInstanceDto[] GetProcessInstances(WebEas.Services.Esb.Bpm2.GetProcessInstancesRequestDto GetProcessInstancesRequestDto) {
            WebEas.Services.Esb.Bpm2.GetProcessInstancesRequest inValue = new WebEas.Services.Esb.Bpm2.GetProcessInstancesRequest();
            inValue.GetProcessInstancesRequestDto = GetProcessInstancesRequestDto;
            WebEas.Services.Esb.Bpm2.GetProcessInstancesResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).GetProcessInstances(inValue);
            return retVal.GetProcessInstancesResponseDto;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.Services.Esb.Bpm2.GetUserAgendaCountResponse WebEas.Services.Esb.Bpm2.BpmServicePortType.GetUserAgendaCount(WebEas.Services.Esb.Bpm2.GetUserAgendaCountRequest request) {
            return base.Channel.GetUserAgendaCount(request);
        }
        
        public WebEas.Services.Esb.Bpm2.UserAgendaCountResponseDto GetUserAgendaCount(WebEas.Services.Esb.Bpm2.UserAgendaCountRequestDto UserAgendaCountRequestDto) {
            WebEas.Services.Esb.Bpm2.GetUserAgendaCountRequest inValue = new WebEas.Services.Esb.Bpm2.GetUserAgendaCountRequest();
            inValue.UserAgendaCountRequestDto = UserAgendaCountRequestDto;
            WebEas.Services.Esb.Bpm2.GetUserAgendaCountResponse retVal = ((WebEas.Services.Esb.Bpm2.BpmServicePortType)(this)).GetUserAgendaCount(inValue);
            return retVal.UserAgendaCountResponseDto;
        }
    }
}
