//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.Services.Esb.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Requests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Requests() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebEas.Services.Esb.Test.Requests", typeof(Requests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;approverId&quot;:&quot;1015e14d-2e03-486b-9a96-c5bc1e21aefa&quot;,&quot;authorId&quot;:&quot;1015e14d-2e03-486b-9a96-c5bc1e21aefa&quot;,&quot;bulkId&quot;:0,&quot;bulkIdSpecified&quot;:false,&quot;caseFileName&quot;:&quot;2018 - TKO - DAN&quot;,&quot;isFinal&quot;:false,&quot;InsertBulkRecordDto&quot;:[{&quot;caseFileId&quot;:0,&quot;caseFileIdSpecified&quot;:false,&quot;confidentiality&quot;:&quot;Pristupne&quot;,&quot;confidentialitySpecified&quot;:true,&quot;correlationId&quot;:902737,&quot;isMonitored&quot;:true,&quot;recordType&quot;:&quot;RozhodnutieMeritorne&quot;,&quot;relatedRecordId&quot;:0,&quot;relatedRecordIdSpecified&quot;:false,&quot;subject&quot;:&quot;Rozhodnutie: 2018 - TKO - DAN,  Dominik NovÃ¡k&quot;,&quot;Deci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InsertBulkRecordTest {
            get {
                return ResourceManager.GetString("InsertBulkRecordTest", resourceCulture);
            }
        }
    }
}
