//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEas.UnitTest.IsoDap {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResErr : ResBase {
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResOk))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResErr))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResBaseList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxAssessmentsList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxOrFeeTypesList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxAssessmentItemTypesList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class CorporateBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string corporateBodyFullNameField;
        
        private string identifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string corporateBodyFullName {
            get {
                return this.corporateBodyFullNameField;
            }
            set {
                this.corporateBodyFullNameField = value;
                this.RaisePropertyChanged("corporateBodyFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("identifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class PhysicalPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string familyNameField;
        
        private string givenNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string familyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
                this.RaisePropertyChanged("familyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string givenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
                this.RaisePropertyChanged("givenName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class PersonData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dcomIDField;
        
        private PhysicalPerson physicalPersonField;
        
        private CorporateBody corporateBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dcomID {
            get {
                return this.dcomIDField;
            }
            set {
                this.dcomIDField = value;
                this.RaisePropertyChanged("dcomID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public PhysicalPerson physicalPerson {
            get {
                return this.physicalPersonField;
            }
            set {
                this.physicalPersonField = value;
                this.RaisePropertyChanged("physicalPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public CorporateBody corporateBody {
            get {
                return this.corporateBodyField;
            }
            set {
                this.corporateBodyField = value;
                this.RaisePropertyChanged("corporateBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class TaxAssessmentItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long taxAssessmentItemIDField;
        
        private TaxAssessmentItemCodeEnum taxAssessmentItemCodeField;
        
        private string taxAssessmentItemSectionField;
        
        private decimal amountField;
        
        private bool accountedField;
        
        private int installmentNumberField;
        
        public TaxAssessmentItem() {
            this.installmentNumberField = 1;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long taxAssessmentItemID {
            get {
                return this.taxAssessmentItemIDField;
            }
            set {
                this.taxAssessmentItemIDField = value;
                this.RaisePropertyChanged("taxAssessmentItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TaxAssessmentItemCodeEnum taxAssessmentItemCode {
            get {
                return this.taxAssessmentItemCodeField;
            }
            set {
                this.taxAssessmentItemCodeField = value;
                this.RaisePropertyChanged("taxAssessmentItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string taxAssessmentItemSection {
            get {
                return this.taxAssessmentItemSectionField;
            }
            set {
                this.taxAssessmentItemSectionField = value;
                this.RaisePropertyChanged("taxAssessmentItemSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool accounted {
            get {
                return this.accountedField;
            }
            set {
                this.accountedField = value;
                this.RaisePropertyChanged("accounted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(1)]
        public int installmentNumber {
            get {
                return this.installmentNumberField;
            }
            set {
                this.installmentNumberField = value;
                this.RaisePropertyChanged("installmentNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public enum TaxAssessmentItemCodeEnum {
        
        /// <remarks/>
        AUT,
        
        /// <remarks/>
        OST,
        
        /// <remarks/>
        BYT,
        
        /// <remarks/>
        HRA,
        
        /// <remarks/>
        PES,
        
        /// <remarks/>
        POZ,
        
        /// <remarks/>
        STA,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        OSO,
        
        /// <remarks/>
        ZAM,
        
        /// <remarks/>
        PPO,
        
        /// <remarks/>
        PPI,
        
        /// <remarks/>
        PPV,
        
        /// <remarks/>
        POK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class TaxAssessmentRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int yearField;
        
        private string taxOrFeeTypeCodeField;
        
        private TaxAssessmentTypeEnum taxAssessmentTypeField;
        
        private System.DateTime assessmentDateField;
        
        private System.DateTime validityDateField;
        
        private System.DateTime maturityDateField;
        
        private long decisionIDField;
        
        private string decisionNumberField;
        
        private string payersReferenceField;
        
        private string collectivePaymentField;
        
        private TaxAssessmentItem[] taxAssessmentItemsField;
        
        private PersonData personField;
        
        private System.Nullable<System.DateTime> dueDate01Field;
        
        private bool dueDate01FieldSpecified;
        
        private System.Nullable<decimal> amount01Field;
        
        private bool amount01FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate02Field;
        
        private bool dueDate02FieldSpecified;
        
        private System.Nullable<decimal> amount02Field;
        
        private bool amount02FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate03Field;
        
        private bool dueDate03FieldSpecified;
        
        private System.Nullable<decimal> amount03Field;
        
        private bool amount03FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate04Field;
        
        private bool dueDate04FieldSpecified;
        
        private System.Nullable<decimal> amount04Field;
        
        private bool amount04FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate05Field;
        
        private bool dueDate05FieldSpecified;
        
        private System.Nullable<decimal> amount05Field;
        
        private bool amount05FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate06Field;
        
        private bool dueDate06FieldSpecified;
        
        private System.Nullable<decimal> amount06Field;
        
        private bool amount06FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate07Field;
        
        private bool dueDate07FieldSpecified;
        
        private System.Nullable<decimal> amount07Field;
        
        private bool amount07FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate08Field;
        
        private bool dueDate08FieldSpecified;
        
        private System.Nullable<decimal> amount08Field;
        
        private bool amount08FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate09Field;
        
        private bool dueDate09FieldSpecified;
        
        private System.Nullable<decimal> amount09Field;
        
        private bool amount09FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate10Field;
        
        private bool dueDate10FieldSpecified;
        
        private System.Nullable<decimal> amount10Field;
        
        private bool amount10FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate11Field;
        
        private bool dueDate11FieldSpecified;
        
        private System.Nullable<decimal> amount11Field;
        
        private bool amount11FieldSpecified;
        
        private System.Nullable<System.DateTime> dueDate12Field;
        
        private bool dueDate12FieldSpecified;
        
        private System.Nullable<decimal> amount12Field;
        
        private bool amount12FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string taxOrFeeTypeCode {
            get {
                return this.taxOrFeeTypeCodeField;
            }
            set {
                this.taxOrFeeTypeCodeField = value;
                this.RaisePropertyChanged("taxOrFeeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TaxAssessmentTypeEnum taxAssessmentType {
            get {
                return this.taxAssessmentTypeField;
            }
            set {
                this.taxAssessmentTypeField = value;
                this.RaisePropertyChanged("taxAssessmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime assessmentDate {
            get {
                return this.assessmentDateField;
            }
            set {
                this.assessmentDateField = value;
                this.RaisePropertyChanged("assessmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime validityDate {
            get {
                return this.validityDateField;
            }
            set {
                this.validityDateField = value;
                this.RaisePropertyChanged("validityDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime maturityDate {
            get {
                return this.maturityDateField;
            }
            set {
                this.maturityDateField = value;
                this.RaisePropertyChanged("maturityDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long decisionID {
            get {
                return this.decisionIDField;
            }
            set {
                this.decisionIDField = value;
                this.RaisePropertyChanged("decisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string decisionNumber {
            get {
                return this.decisionNumberField;
            }
            set {
                this.decisionNumberField = value;
                this.RaisePropertyChanged("decisionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string payersReference {
            get {
                return this.payersReferenceField;
            }
            set {
                this.payersReferenceField = value;
                this.RaisePropertyChanged("payersReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string collectivePayment {
            get {
                return this.collectivePaymentField;
            }
            set {
                this.collectivePaymentField = value;
                this.RaisePropertyChanged("collectivePayment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("taxAssessmentItem", IsNullable=false)]
        public TaxAssessmentItem[] taxAssessmentItems {
            get {
                return this.taxAssessmentItemsField;
            }
            set {
                this.taxAssessmentItemsField = value;
                this.RaisePropertyChanged("taxAssessmentItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public PersonData person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
                this.RaisePropertyChanged("person");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> dueDate01 {
            get {
                return this.dueDate01Field;
            }
            set {
                this.dueDate01Field = value;
                this.RaisePropertyChanged("dueDate01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate01Specified {
            get {
                return this.dueDate01FieldSpecified;
            }
            set {
                this.dueDate01FieldSpecified = value;
                this.RaisePropertyChanged("dueDate01Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> amount01 {
            get {
                return this.amount01Field;
            }
            set {
                this.amount01Field = value;
                this.RaisePropertyChanged("amount01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount01Specified {
            get {
                return this.amount01FieldSpecified;
            }
            set {
                this.amount01FieldSpecified = value;
                this.RaisePropertyChanged("amount01Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=14)]
        public System.Nullable<System.DateTime> dueDate02 {
            get {
                return this.dueDate02Field;
            }
            set {
                this.dueDate02Field = value;
                this.RaisePropertyChanged("dueDate02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate02Specified {
            get {
                return this.dueDate02FieldSpecified;
            }
            set {
                this.dueDate02FieldSpecified = value;
                this.RaisePropertyChanged("dueDate02Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> amount02 {
            get {
                return this.amount02Field;
            }
            set {
                this.amount02Field = value;
                this.RaisePropertyChanged("amount02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount02Specified {
            get {
                return this.amount02FieldSpecified;
            }
            set {
                this.amount02FieldSpecified = value;
                this.RaisePropertyChanged("amount02Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> dueDate03 {
            get {
                return this.dueDate03Field;
            }
            set {
                this.dueDate03Field = value;
                this.RaisePropertyChanged("dueDate03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate03Specified {
            get {
                return this.dueDate03FieldSpecified;
            }
            set {
                this.dueDate03FieldSpecified = value;
                this.RaisePropertyChanged("dueDate03Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> amount03 {
            get {
                return this.amount03Field;
            }
            set {
                this.amount03Field = value;
                this.RaisePropertyChanged("amount03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount03Specified {
            get {
                return this.amount03FieldSpecified;
            }
            set {
                this.amount03FieldSpecified = value;
                this.RaisePropertyChanged("amount03Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> dueDate04 {
            get {
                return this.dueDate04Field;
            }
            set {
                this.dueDate04Field = value;
                this.RaisePropertyChanged("dueDate04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate04Specified {
            get {
                return this.dueDate04FieldSpecified;
            }
            set {
                this.dueDate04FieldSpecified = value;
                this.RaisePropertyChanged("dueDate04Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> amount04 {
            get {
                return this.amount04Field;
            }
            set {
                this.amount04Field = value;
                this.RaisePropertyChanged("amount04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount04Specified {
            get {
                return this.amount04FieldSpecified;
            }
            set {
                this.amount04FieldSpecified = value;
                this.RaisePropertyChanged("amount04Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> dueDate05 {
            get {
                return this.dueDate05Field;
            }
            set {
                this.dueDate05Field = value;
                this.RaisePropertyChanged("dueDate05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate05Specified {
            get {
                return this.dueDate05FieldSpecified;
            }
            set {
                this.dueDate05FieldSpecified = value;
                this.RaisePropertyChanged("dueDate05Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<decimal> amount05 {
            get {
                return this.amount05Field;
            }
            set {
                this.amount05Field = value;
                this.RaisePropertyChanged("amount05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount05Specified {
            get {
                return this.amount05FieldSpecified;
            }
            set {
                this.amount05FieldSpecified = value;
                this.RaisePropertyChanged("amount05Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=22)]
        public System.Nullable<System.DateTime> dueDate06 {
            get {
                return this.dueDate06Field;
            }
            set {
                this.dueDate06Field = value;
                this.RaisePropertyChanged("dueDate06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate06Specified {
            get {
                return this.dueDate06FieldSpecified;
            }
            set {
                this.dueDate06FieldSpecified = value;
                this.RaisePropertyChanged("dueDate06Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<decimal> amount06 {
            get {
                return this.amount06Field;
            }
            set {
                this.amount06Field = value;
                this.RaisePropertyChanged("amount06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount06Specified {
            get {
                return this.amount06FieldSpecified;
            }
            set {
                this.amount06FieldSpecified = value;
                this.RaisePropertyChanged("amount06Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> dueDate07 {
            get {
                return this.dueDate07Field;
            }
            set {
                this.dueDate07Field = value;
                this.RaisePropertyChanged("dueDate07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate07Specified {
            get {
                return this.dueDate07FieldSpecified;
            }
            set {
                this.dueDate07FieldSpecified = value;
                this.RaisePropertyChanged("dueDate07Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<decimal> amount07 {
            get {
                return this.amount07Field;
            }
            set {
                this.amount07Field = value;
                this.RaisePropertyChanged("amount07");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount07Specified {
            get {
                return this.amount07FieldSpecified;
            }
            set {
                this.amount07FieldSpecified = value;
                this.RaisePropertyChanged("amount07Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=26)]
        public System.Nullable<System.DateTime> dueDate08 {
            get {
                return this.dueDate08Field;
            }
            set {
                this.dueDate08Field = value;
                this.RaisePropertyChanged("dueDate08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate08Specified {
            get {
                return this.dueDate08FieldSpecified;
            }
            set {
                this.dueDate08FieldSpecified = value;
                this.RaisePropertyChanged("dueDate08Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<decimal> amount08 {
            get {
                return this.amount08Field;
            }
            set {
                this.amount08Field = value;
                this.RaisePropertyChanged("amount08");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount08Specified {
            get {
                return this.amount08FieldSpecified;
            }
            set {
                this.amount08FieldSpecified = value;
                this.RaisePropertyChanged("amount08Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=28)]
        public System.Nullable<System.DateTime> dueDate09 {
            get {
                return this.dueDate09Field;
            }
            set {
                this.dueDate09Field = value;
                this.RaisePropertyChanged("dueDate09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate09Specified {
            get {
                return this.dueDate09FieldSpecified;
            }
            set {
                this.dueDate09FieldSpecified = value;
                this.RaisePropertyChanged("dueDate09Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<decimal> amount09 {
            get {
                return this.amount09Field;
            }
            set {
                this.amount09Field = value;
                this.RaisePropertyChanged("amount09");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount09Specified {
            get {
                return this.amount09FieldSpecified;
            }
            set {
                this.amount09FieldSpecified = value;
                this.RaisePropertyChanged("amount09Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=30)]
        public System.Nullable<System.DateTime> dueDate10 {
            get {
                return this.dueDate10Field;
            }
            set {
                this.dueDate10Field = value;
                this.RaisePropertyChanged("dueDate10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate10Specified {
            get {
                return this.dueDate10FieldSpecified;
            }
            set {
                this.dueDate10FieldSpecified = value;
                this.RaisePropertyChanged("dueDate10Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> amount10 {
            get {
                return this.amount10Field;
            }
            set {
                this.amount10Field = value;
                this.RaisePropertyChanged("amount10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount10Specified {
            get {
                return this.amount10FieldSpecified;
            }
            set {
                this.amount10FieldSpecified = value;
                this.RaisePropertyChanged("amount10Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> dueDate11 {
            get {
                return this.dueDate11Field;
            }
            set {
                this.dueDate11Field = value;
                this.RaisePropertyChanged("dueDate11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate11Specified {
            get {
                return this.dueDate11FieldSpecified;
            }
            set {
                this.dueDate11FieldSpecified = value;
                this.RaisePropertyChanged("dueDate11Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public System.Nullable<decimal> amount11 {
            get {
                return this.amount11Field;
            }
            set {
                this.amount11Field = value;
                this.RaisePropertyChanged("amount11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount11Specified {
            get {
                return this.amount11FieldSpecified;
            }
            set {
                this.amount11FieldSpecified = value;
                this.RaisePropertyChanged("amount11Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=34)]
        public System.Nullable<System.DateTime> dueDate12 {
            get {
                return this.dueDate12Field;
            }
            set {
                this.dueDate12Field = value;
                this.RaisePropertyChanged("dueDate12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dueDate12Specified {
            get {
                return this.dueDate12FieldSpecified;
            }
            set {
                this.dueDate12FieldSpecified = value;
                this.RaisePropertyChanged("dueDate12Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<decimal> amount12 {
            get {
                return this.amount12Field;
            }
            set {
                this.amount12Field = value;
                this.RaisePropertyChanged("amount12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amount12Specified {
            get {
                return this.amount12FieldSpecified;
            }
            set {
                this.amount12FieldSpecified = value;
                this.RaisePropertyChanged("amount12Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public enum TaxAssessmentTypeEnum {
        
        /// <remarks/>
        DAN,
        
        /// <remarks/>
        ODP,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        POK,
        
        /// <remarks/>
        URO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class TaxOrFeeTypeRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string typeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("typeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class TaxAssessmentItemTypeRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taxOrFeeTypeCodeField;
        
        private int yearField;
        
        private TaxAssessmentTypeEnum taxAssessmentTypeField;
        
        private TaxAssessmentItemCodeEnum taxAssessmentItemCodeField;
        
        private string taxAssessmentItemSectionField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taxOrFeeTypeCode {
            get {
                return this.taxOrFeeTypeCodeField;
            }
            set {
                this.taxOrFeeTypeCodeField = value;
                this.RaisePropertyChanged("taxOrFeeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TaxAssessmentTypeEnum taxAssessmentType {
            get {
                return this.taxAssessmentTypeField;
            }
            set {
                this.taxAssessmentTypeField = value;
                this.RaisePropertyChanged("taxAssessmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TaxAssessmentItemCodeEnum taxAssessmentItemCode {
            get {
                return this.taxAssessmentItemCodeField;
            }
            set {
                this.taxAssessmentItemCodeField = value;
                this.RaisePropertyChanged("taxAssessmentItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string taxAssessmentItemSection {
            get {
                return this.taxAssessmentItemSectionField;
            }
            set {
                this.taxAssessmentItemSectionField = value;
                this.RaisePropertyChanged("taxAssessmentItemSection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class TaxAssessmentRecordStatusRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> decisionIDField;
        
        private bool decisionIDFieldSpecified;
        
        private System.Nullable<long> taxAssessmentItemIDField;
        
        private bool taxAssessmentItemIDFieldSpecified;
        
        private bool accountedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> decisionID {
            get {
                return this.decisionIDField;
            }
            set {
                this.decisionIDField = value;
                this.RaisePropertyChanged("decisionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool decisionIDSpecified {
            get {
                return this.decisionIDFieldSpecified;
            }
            set {
                this.decisionIDFieldSpecified = value;
                this.RaisePropertyChanged("decisionIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<long> taxAssessmentItemID {
            get {
                return this.taxAssessmentItemIDField;
            }
            set {
                this.taxAssessmentItemIDField = value;
                this.RaisePropertyChanged("taxAssessmentItemID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxAssessmentItemIDSpecified {
            get {
                return this.taxAssessmentItemIDFieldSpecified;
            }
            set {
                this.taxAssessmentItemIDFieldSpecified = value;
                this.RaisePropertyChanged("taxAssessmentItemIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool accounted {
            get {
                return this.accountedField;
            }
            set {
                this.accountedField = value;
                this.RaisePropertyChanged("accounted");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReqBaseList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReqSetTaxAssessmentsRecordStatusList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReqGetTaxAssessments))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReqGetTaxAssessmentItemTypes))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ReqBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReqSetTaxAssessmentsRecordStatusList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ReqBaseList : ReqBase {
        
        private int recordCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ReqSetTaxAssessmentsRecordStatusList : ReqBaseList {
        
        private TaxAssessmentRecordStatusRecord[] requestRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
        public TaxAssessmentRecordStatusRecord[] requestRecords {
            get {
                return this.requestRecordsField;
            }
            set {
                this.requestRecordsField = value;
                this.RaisePropertyChanged("requestRecords");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ReqGetTaxAssessments : ReqBase {
        
        private string taxOrFeeTypeCodeField;
        
        private System.Nullable<int> yearField;
        
        private bool yearFieldSpecified;
        
        private System.Nullable<TaxAssessmentTypeEnum> taxAssessmentTypeField;
        
        private bool taxAssessmentTypeFieldSpecified;
        
        private System.Nullable<System.DateTime> dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.Nullable<System.DateTime> dateToField;
        
        private bool dateToFieldSpecified;
        
        private System.Nullable<bool> unaccountedOnlyField;
        
        private bool unaccountedOnlyFieldSpecified;
        
        private System.Nullable<bool> useAssessmentDateField;
        
        private string variableSymbolField;
        
        private string identificationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string taxOrFeeTypeCode {
            get {
                return this.taxOrFeeTypeCodeField;
            }
            set {
                this.taxOrFeeTypeCodeField = value;
                this.RaisePropertyChanged("taxOrFeeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<TaxAssessmentTypeEnum> taxAssessmentType {
            get {
                return this.taxAssessmentTypeField;
            }
            set {
                this.taxAssessmentTypeField = value;
                this.RaisePropertyChanged("taxAssessmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool taxAssessmentTypeSpecified {
            get {
                return this.taxAssessmentTypeFieldSpecified;
            }
            set {
                this.taxAssessmentTypeFieldSpecified = value;
                this.RaisePropertyChanged("taxAssessmentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateFromSpecified {
            get {
                return this.dateFromFieldSpecified;
            }
            set {
                this.dateFromFieldSpecified = value;
                this.RaisePropertyChanged("dateFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateToSpecified {
            get {
                return this.dateToFieldSpecified;
            }
            set {
                this.dateToFieldSpecified = value;
                this.RaisePropertyChanged("dateToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> unaccountedOnly {
            get {
                return this.unaccountedOnlyField;
            }
            set {
                this.unaccountedOnlyField = value;
                this.RaisePropertyChanged("unaccountedOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unaccountedOnlySpecified {
            get {
                return this.unaccountedOnlyFieldSpecified;
            }
            set {
                this.unaccountedOnlyFieldSpecified = value;
                this.RaisePropertyChanged("unaccountedOnlySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> useAssessmentDate {
            get {
                return this.useAssessmentDateField;
            }
            set {
                this.useAssessmentDateField = value;
                this.RaisePropertyChanged("useAssessmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string variableSymbol {
            get {
                return this.variableSymbolField;
            }
            set {
                this.variableSymbolField = value;
                this.RaisePropertyChanged("variableSymbol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string identificationNumber {
            get {
                return this.identificationNumberField;
            }
            set {
                this.identificationNumberField = value;
                this.RaisePropertyChanged("identificationNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ReqGetTaxAssessmentItemTypes : ReqBase {
        
        private string taxOrFeeTypeCodeField;
        
        private System.Nullable<int> yearField;
        
        private bool yearFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string taxOrFeeTypeCode {
            get {
                return this.taxOrFeeTypeCodeField;
            }
            set {
                this.taxOrFeeTypeCodeField = value;
                this.RaisePropertyChanged("taxOrFeeTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearSpecified {
            get {
                return this.yearFieldSpecified;
            }
            set {
                this.yearFieldSpecified = value;
                this.RaisePropertyChanged("yearSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResOk : ResBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxAssessmentsList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxOrFeeTypesList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResGetTaxAssessmentItemTypesList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResBaseList : ResBase {
        
        private int recordCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int recordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
                this.RaisePropertyChanged("recordCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResGetTaxAssessmentsList : ResBaseList {
        
        private TaxAssessmentRecord[] resultRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
        public TaxAssessmentRecord[] resultRecords {
            get {
                return this.resultRecordsField;
            }
            set {
                this.resultRecordsField = value;
                this.RaisePropertyChanged("resultRecords");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResGetTaxOrFeeTypesList : ResBaseList {
        
        private TaxOrFeeTypeRecord[] resultRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
        public TaxOrFeeTypeRecord[] resultRecords {
            get {
                return this.resultRecordsField;
            }
            set {
                this.resultRecordsField = value;
                this.RaisePropertyChanged("resultRecords");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class ResGetTaxAssessmentItemTypesList : ResBaseList {
        
        private TaxAssessmentItemTypeRecord[] resultRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("record", IsNullable=false)]
        public TaxAssessmentItemTypeRecord[] resultRecords {
            get {
                return this.resultRecordsField;
            }
            set {
                this.resultRecordsField = value;
                this.RaisePropertyChanged("resultRecords");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.dcom.sk/integration/dap", ConfigurationName="IsoDap.IDanePoplatky")]
    public interface IDanePoplatky {
        
        // CODEGEN: Generating message contract since the operation getTaxAssessmentItemTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxAssessmentItemTypeReq", ReplyAction="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxAssessmentItemTypeRes")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.UnitTest.IsoDap.ResErr), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ResErr")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReqBase))]
        WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeRes getTaxAssessmentItemTypes(WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeReq request);
        
        // CODEGEN: Generating message contract since the operation getTaxOrFeeTypes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxOrFeeTypesReq", ReplyAction="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxOrFeeTypesRes")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.UnitTest.IsoDap.ResErr), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ResErr")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReqBase))]
        WebEas.UnitTest.IsoDap.getTaxOrFeeTypesRes getTaxOrFeeTypes(WebEas.UnitTest.IsoDap.getTaxOrFeeTypesReq request);
        
        // CODEGEN: Generating message contract since the operation getTaxAssessments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxAssessmentsReq", ReplyAction="http://schemas.dcom.sk/integration/dap/IDanePoplatky/getTaxAssessmentsRes")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.UnitTest.IsoDap.ResErr), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ResErr")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReqBase))]
        WebEas.UnitTest.IsoDap.getTaxAssessmentsRes getTaxAssessments(WebEas.UnitTest.IsoDap.getTaxAssessmentsReq request);
        
        // CODEGEN: Generating message contract since the operation setTaxAssessmentsRecordStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.dcom.sk/integration/dap/IDanePoplatky/setTaxAssessmentsRecordStatu" +
            "sReq", ReplyAction="http://schemas.dcom.sk/integration/dap/IDanePoplatky/setTaxAssessmentsRecordStatu" +
            "sRes")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebEas.UnitTest.IsoDap.ResErr), Action="http://www.w3.org/2005/08/addressing/soap/fault", Name="ResErr")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ReqBase))]
        WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusRes setTaxAssessmentsRecordStatus(WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusReq request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
    public partial class DcmHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestIdField;
        
        private string tenantIdField;
        
        private string isoIdField;
        
        private string officeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("requestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("tenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string isoId {
            get {
                return this.isoIdField;
            }
            set {
                this.isoIdField = value;
                this.RaisePropertyChanged("isoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string officeId {
            get {
                return this.officeIdField;
            }
            set {
                this.officeIdField = value;
                this.RaisePropertyChanged("officeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxAssessmentItemTypeReq {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ReqGetTaxAssessmentItemTypes ReqGetTaxAssessmentItemTypes;
        
        public getTaxAssessmentItemTypeReq() {
        }
        
        public getTaxAssessmentItemTypeReq(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqGetTaxAssessmentItemTypes ReqGetTaxAssessmentItemTypes) {
            this.DcmHeader = DcmHeader;
            this.ReqGetTaxAssessmentItemTypes = ReqGetTaxAssessmentItemTypes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxAssessmentItemTypeRes {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ResGetTaxAssessmentItemTypesList ResGetTaxAssessmentItemTypesList;
        
        public getTaxAssessmentItemTypeRes() {
        }
        
        public getTaxAssessmentItemTypeRes(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ResGetTaxAssessmentItemTypesList ResGetTaxAssessmentItemTypesList) {
            this.DcmHeader = DcmHeader;
            this.ResGetTaxAssessmentItemTypesList = ResGetTaxAssessmentItemTypesList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxOrFeeTypesReq {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ReqBase ReqBase;
        
        public getTaxOrFeeTypesReq() {
        }
        
        public getTaxOrFeeTypesReq(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqBase ReqBase) {
            this.DcmHeader = DcmHeader;
            this.ReqBase = ReqBase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxOrFeeTypesRes {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ResGetTaxOrFeeTypesList ResGetTaxOrFeeTypesList;
        
        public getTaxOrFeeTypesRes() {
        }
        
        public getTaxOrFeeTypesRes(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ResGetTaxOrFeeTypesList ResGetTaxOrFeeTypesList) {
            this.DcmHeader = DcmHeader;
            this.ResGetTaxOrFeeTypesList = ResGetTaxOrFeeTypesList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxAssessmentsReq {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ReqGetTaxAssessments ReqGetTaxAssessments;
        
        public getTaxAssessmentsReq() {
        }
        
        public getTaxAssessmentsReq(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqGetTaxAssessments ReqGetTaxAssessments) {
            this.DcmHeader = DcmHeader;
            this.ReqGetTaxAssessments = ReqGetTaxAssessments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTaxAssessmentsRes {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ResGetTaxAssessmentsList ResGetTaxAssessmentsList;
        
        public getTaxAssessmentsRes() {
        }
        
        public getTaxAssessmentsRes(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ResGetTaxAssessmentsList ResGetTaxAssessmentsList) {
            this.DcmHeader = DcmHeader;
            this.ResGetTaxAssessmentsList = ResGetTaxAssessmentsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setTaxAssessmentsRecordStatusReq {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ReqSetTaxAssessmentsRecordStatusList ReqSetTaxAssessmentsRecordStatusList;
        
        public setTaxAssessmentsRecordStatusReq() {
        }
        
        public setTaxAssessmentsRecordStatusReq(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqSetTaxAssessmentsRecordStatusList ReqSetTaxAssessmentsRecordStatusList) {
            this.DcmHeader = DcmHeader;
            this.ReqSetTaxAssessmentsRecordStatusList = ReqSetTaxAssessmentsRecordStatusList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setTaxAssessmentsRecordStatusRes {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.dcom.sk/integration/dap")]
        public WebEas.UnitTest.IsoDap.DcmHeader DcmHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.dcom.sk/integration/dap", Order=0)]
        public WebEas.UnitTest.IsoDap.ResBase ResBase;
        
        public setTaxAssessmentsRecordStatusRes() {
        }
        
        public setTaxAssessmentsRecordStatusRes(WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ResBase ResBase) {
            this.DcmHeader = DcmHeader;
            this.ResBase = ResBase;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDanePoplatkyChannel : WebEas.UnitTest.IsoDap.IDanePoplatky, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DanePoplatkyClient : System.ServiceModel.ClientBase<WebEas.UnitTest.IsoDap.IDanePoplatky>, WebEas.UnitTest.IsoDap.IDanePoplatky {
        
        public DanePoplatkyClient() {
        }
        
        public DanePoplatkyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DanePoplatkyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanePoplatkyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DanePoplatkyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeRes WebEas.UnitTest.IsoDap.IDanePoplatky.getTaxAssessmentItemTypes(WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeReq request) {
            return base.Channel.getTaxAssessmentItemTypes(request);
        }
        
        public WebEas.UnitTest.IsoDap.ResGetTaxAssessmentItemTypesList getTaxAssessmentItemTypes(ref WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqGetTaxAssessmentItemTypes ReqGetTaxAssessmentItemTypes) {
            WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeReq inValue = new WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeReq();
            inValue.DcmHeader = DcmHeader;
            inValue.ReqGetTaxAssessmentItemTypes = ReqGetTaxAssessmentItemTypes;
            WebEas.UnitTest.IsoDap.getTaxAssessmentItemTypeRes retVal = ((WebEas.UnitTest.IsoDap.IDanePoplatky)(this)).getTaxAssessmentItemTypes(inValue);
            DcmHeader = retVal.DcmHeader;
            return retVal.ResGetTaxAssessmentItemTypesList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.UnitTest.IsoDap.getTaxOrFeeTypesRes WebEas.UnitTest.IsoDap.IDanePoplatky.getTaxOrFeeTypes(WebEas.UnitTest.IsoDap.getTaxOrFeeTypesReq request) {
            return base.Channel.getTaxOrFeeTypes(request);
        }
        
        public WebEas.UnitTest.IsoDap.ResGetTaxOrFeeTypesList getTaxOrFeeTypes(ref WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqBase ReqBase) {
            WebEas.UnitTest.IsoDap.getTaxOrFeeTypesReq inValue = new WebEas.UnitTest.IsoDap.getTaxOrFeeTypesReq();
            inValue.DcmHeader = DcmHeader;
            inValue.ReqBase = ReqBase;
            WebEas.UnitTest.IsoDap.getTaxOrFeeTypesRes retVal = ((WebEas.UnitTest.IsoDap.IDanePoplatky)(this)).getTaxOrFeeTypes(inValue);
            DcmHeader = retVal.DcmHeader;
            return retVal.ResGetTaxOrFeeTypesList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.UnitTest.IsoDap.getTaxAssessmentsRes WebEas.UnitTest.IsoDap.IDanePoplatky.getTaxAssessments(WebEas.UnitTest.IsoDap.getTaxAssessmentsReq request) {
            return base.Channel.getTaxAssessments(request);
        }
        
        public WebEas.UnitTest.IsoDap.ResGetTaxAssessmentsList getTaxAssessments(ref WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqGetTaxAssessments ReqGetTaxAssessments) {
            WebEas.UnitTest.IsoDap.getTaxAssessmentsReq inValue = new WebEas.UnitTest.IsoDap.getTaxAssessmentsReq();
            inValue.DcmHeader = DcmHeader;
            inValue.ReqGetTaxAssessments = ReqGetTaxAssessments;
            WebEas.UnitTest.IsoDap.getTaxAssessmentsRes retVal = ((WebEas.UnitTest.IsoDap.IDanePoplatky)(this)).getTaxAssessments(inValue);
            DcmHeader = retVal.DcmHeader;
            return retVal.ResGetTaxAssessmentsList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusRes WebEas.UnitTest.IsoDap.IDanePoplatky.setTaxAssessmentsRecordStatus(WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusReq request) {
            return base.Channel.setTaxAssessmentsRecordStatus(request);
        }
        
        public WebEas.UnitTest.IsoDap.ResBase setTaxAssessmentsRecordStatus(ref WebEas.UnitTest.IsoDap.DcmHeader DcmHeader, WebEas.UnitTest.IsoDap.ReqSetTaxAssessmentsRecordStatusList ReqSetTaxAssessmentsRecordStatusList) {
            WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusReq inValue = new WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusReq();
            inValue.DcmHeader = DcmHeader;
            inValue.ReqSetTaxAssessmentsRecordStatusList = ReqSetTaxAssessmentsRecordStatusList;
            WebEas.UnitTest.IsoDap.setTaxAssessmentsRecordStatusRes retVal = ((WebEas.UnitTest.IsoDap.IDanePoplatky)(this)).setTaxAssessmentsRecordStatus(inValue);
            DcmHeader = retVal.DcmHeader;
            return retVal.ResBase;
        }
    }
}
